[2023-09-15T15:32:59.354+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: eCommerce_ETL_dag.branching manual__2023-09-15T15:32:56.958527+00:00 [queued]>
[2023-09-15T15:32:59.374+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: eCommerce_ETL_dag.branching manual__2023-09-15T15:32:56.958527+00:00 [queued]>
[2023-09-15T15:32:59.375+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 2
[2023-09-15T15:32:59.400+0000] {taskinstance.py:1327} INFO - Executing <Task(BranchPythonOperator): branching> on 2023-09-15 15:32:56.958527+00:00
[2023-09-15T15:32:59.410+0000] {standard_task_runner.py:57} INFO - Started process 340 to run task
[2023-09-15T15:32:59.422+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'eCommerce_ETL_dag', 'branching', 'manual__2023-09-15T15:32:56.958527+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/workflow.py', '--cfg-path', '/tmp/tmprjbhla7x']
[2023-09-15T15:32:59.430+0000] {standard_task_runner.py:85} INFO - Job 6: Subtask branching
[2023-09-15T15:32:59.581+0000] {task_command.py:410} INFO - Running <TaskInstance: eCommerce_ETL_dag.branching manual__2023-09-15T15:32:56.958527+00:00 [running]> on host 228226a2581e
[2023-09-15T15:32:59.733+0000] {taskinstance.py:1545} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='eCommerce_ETL_dag' AIRFLOW_CTX_TASK_ID='branching' AIRFLOW_CTX_EXECUTION_DATE='2023-09-15T15:32:56.958527+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-09-15T15:32:56.958527+00:00'
[2023-09-15T15:32:59.746+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 215, in execute
    branch = super().execute(context)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/workflow.py", line 27, in check_table_count
    check = cursor.fetchone()[0]
TypeError: 'NoneType' object is not subscriptable
[2023-09-15T15:32:59.762+0000] {taskinstance.py:1345} INFO - Marking task as UP_FOR_RETRY. dag_id=eCommerce_ETL_dag, task_id=branching, execution_date=20230915T153256, start_date=20230915T153259, end_date=20230915T153259
[2023-09-15T15:32:59.780+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 6 for task branching ('NoneType' object is not subscriptable; 340)
[2023-09-15T15:32:59.803+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-09-15T15:32:59.860+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
