[2023-08-25T09:58:07.653+0000] {processor.py:157} INFO - Started process (PID=163) to work on /opt/airflow/dags/workflow.py
[2023-08-25T09:58:07.681+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/workflow.py for tasks to queue
[2023-08-25T09:58:07.700+0000] {logging_mixin.py:150} INFO - [2023-08-25T09:58:07.700+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/workflow.py
[2023-08-25T09:58:07.865+0000] {logging_mixin.py:150} INFO - [2023-08-25T09:58:07.841+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/workflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/workflow.py", line 1, in <module>
    from python_data_maker import pre_generate_log,generate_log,generate_item,generate_rating,generate_user
  File "/opt/airflow/dags/python_data_maker/pre_generate_log.py", line 1, in <module>
    from faker import Faker
ModuleNotFoundError: No module named 'faker'
[2023-08-25T09:58:07.868+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/workflow.py
[2023-08-25T09:58:08.067+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/workflow.py took 0.437 seconds
[2023-08-25T09:58:39.553+0000] {processor.py:157} INFO - Started process (PID=175) to work on /opt/airflow/dags/workflow.py
[2023-08-25T09:58:39.613+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/workflow.py for tasks to queue
[2023-08-25T09:58:39.639+0000] {logging_mixin.py:150} INFO - [2023-08-25T09:58:39.638+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/workflow.py
[2023-08-25T09:58:39.789+0000] {logging_mixin.py:150} INFO - [2023-08-25T09:58:39.751+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/workflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/workflow.py", line 1, in <module>
    from python_data_maker import pre_generate_log,generate_log,generate_item,generate_rating,generate_user
  File "/opt/airflow/dags/python_data_maker/pre_generate_log.py", line 1, in <module>
    from faker import Faker
ModuleNotFoundError: No module named 'faker'
[2023-08-25T09:58:39.818+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/workflow.py
[2023-08-25T09:58:41.840+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/workflow.py took 2.438 seconds
[2023-08-25T09:59:12.220+0000] {processor.py:157} INFO - Started process (PID=187) to work on /opt/airflow/dags/workflow.py
[2023-08-25T09:59:12.223+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/workflow.py for tasks to queue
[2023-08-25T09:59:12.226+0000] {logging_mixin.py:150} INFO - [2023-08-25T09:59:12.225+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/workflow.py
[2023-08-25T09:59:12.259+0000] {logging_mixin.py:150} INFO - [2023-08-25T09:59:12.254+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/workflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/workflow.py", line 1, in <module>
    from python_data_maker import pre_generate_log,generate_log,generate_item,generate_rating,generate_user
  File "/opt/airflow/dags/python_data_maker/pre_generate_log.py", line 1, in <module>
    from faker import Faker
ModuleNotFoundError: No module named 'faker'
[2023-08-25T09:59:12.261+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/workflow.py
[2023-08-25T09:59:12.300+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/workflow.py took 0.087 seconds
[2023-08-25T09:59:42.730+0000] {processor.py:157} INFO - Started process (PID=200) to work on /opt/airflow/dags/workflow.py
[2023-08-25T09:59:42.734+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/workflow.py for tasks to queue
[2023-08-25T09:59:42.738+0000] {logging_mixin.py:150} INFO - [2023-08-25T09:59:42.737+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/workflow.py
[2023-08-25T09:59:42.780+0000] {logging_mixin.py:150} INFO - [2023-08-25T09:59:42.769+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/workflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/workflow.py", line 1, in <module>
    from python_data_maker import pre_generate_log,generate_log,generate_item,generate_rating,generate_user
  File "/opt/airflow/dags/python_data_maker/pre_generate_log.py", line 1, in <module>
    from faker import Faker
ModuleNotFoundError: No module named 'faker'
[2023-08-25T09:59:42.782+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/workflow.py
[2023-08-25T09:59:42.925+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/workflow.py took 0.215 seconds
[2023-08-25T10:00:13.104+0000] {processor.py:157} INFO - Started process (PID=212) to work on /opt/airflow/dags/workflow.py
[2023-08-25T10:00:13.107+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/workflow.py for tasks to queue
[2023-08-25T10:00:13.113+0000] {logging_mixin.py:150} INFO - [2023-08-25T10:00:13.110+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/workflow.py
[2023-08-25T10:00:13.154+0000] {logging_mixin.py:150} INFO - [2023-08-25T10:00:13.143+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/workflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/workflow.py", line 1, in <module>
    from python_data_maker import pre_generate_log,generate_log,generate_item,generate_rating,generate_user
  File "/opt/airflow/dags/python_data_maker/pre_generate_log.py", line 1, in <module>
    from faker import Faker
ModuleNotFoundError: No module named 'faker'
[2023-08-25T10:00:13.158+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/workflow.py
[2023-08-25T10:00:13.216+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/workflow.py took 0.125 seconds
[2023-08-25T10:00:43.709+0000] {processor.py:157} INFO - Started process (PID=224) to work on /opt/airflow/dags/workflow.py
[2023-08-25T10:00:43.717+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/workflow.py for tasks to queue
[2023-08-25T10:00:43.726+0000] {logging_mixin.py:150} INFO - [2023-08-25T10:00:43.720+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/workflow.py
[2023-08-25T10:00:43.827+0000] {logging_mixin.py:150} INFO - [2023-08-25T10:00:43.814+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/workflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/workflow.py", line 1, in <module>
    from python_data_maker import pre_generate_log,generate_log,generate_item,generate_rating,generate_user
  File "/opt/airflow/dags/python_data_maker/pre_generate_log.py", line 1, in <module>
    from faker import Faker
ModuleNotFoundError: No module named 'faker'
[2023-08-25T10:00:43.832+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/workflow.py
[2023-08-25T10:00:44.121+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/workflow.py took 0.438 seconds
[2023-08-25T10:01:14.620+0000] {processor.py:157} INFO - Started process (PID=235) to work on /opt/airflow/dags/workflow.py
[2023-08-25T10:01:14.627+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/workflow.py for tasks to queue
[2023-08-25T10:01:14.631+0000] {logging_mixin.py:150} INFO - [2023-08-25T10:01:14.630+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/workflow.py
[2023-08-25T10:01:14.689+0000] {logging_mixin.py:150} INFO - [2023-08-25T10:01:14.678+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/workflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/workflow.py", line 1, in <module>
    from python_data_maker import pre_generate_log,generate_log,generate_item,generate_rating,generate_user
  File "/opt/airflow/dags/python_data_maker/pre_generate_log.py", line 1, in <module>
    from faker import Faker
ModuleNotFoundError: No module named 'faker'
[2023-08-25T10:01:14.693+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/workflow.py
[2023-08-25T10:01:14.748+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/workflow.py took 0.135 seconds
[2023-08-25T10:01:45.077+0000] {processor.py:157} INFO - Started process (PID=247) to work on /opt/airflow/dags/workflow.py
[2023-08-25T10:01:45.084+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/workflow.py for tasks to queue
[2023-08-25T10:01:45.089+0000] {logging_mixin.py:150} INFO - [2023-08-25T10:01:45.088+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/workflow.py
[2023-08-25T10:01:45.138+0000] {logging_mixin.py:150} INFO - [2023-08-25T10:01:45.123+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/workflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/workflow.py", line 1, in <module>
    from python_data_maker import pre_generate_log,generate_log,generate_item,generate_rating,generate_user
  File "/opt/airflow/dags/python_data_maker/pre_generate_log.py", line 1, in <module>
    from faker import Faker
ModuleNotFoundError: No module named 'faker'
[2023-08-25T10:01:45.146+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/workflow.py
[2023-08-25T10:01:45.255+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/workflow.py took 0.191 seconds
[2023-08-25T10:02:15.469+0000] {processor.py:157} INFO - Started process (PID=259) to work on /opt/airflow/dags/workflow.py
[2023-08-25T10:02:15.471+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/workflow.py for tasks to queue
[2023-08-25T10:02:15.474+0000] {logging_mixin.py:150} INFO - [2023-08-25T10:02:15.474+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/workflow.py
[2023-08-25T10:02:15.505+0000] {logging_mixin.py:150} INFO - [2023-08-25T10:02:15.500+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/workflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/workflow.py", line 1, in <module>
    from python_data_maker import pre_generate_log,generate_log,generate_item,generate_rating,generate_user
  File "/opt/airflow/dags/python_data_maker/pre_generate_log.py", line 1, in <module>
    from faker import Faker
ModuleNotFoundError: No module named 'faker'
[2023-08-25T10:02:15.509+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/workflow.py
[2023-08-25T10:02:15.548+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/workflow.py took 0.087 seconds
[2023-08-25T10:02:45.773+0000] {processor.py:157} INFO - Started process (PID=271) to work on /opt/airflow/dags/workflow.py
[2023-08-25T10:02:45.781+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/workflow.py for tasks to queue
[2023-08-25T10:02:45.789+0000] {logging_mixin.py:150} INFO - [2023-08-25T10:02:45.788+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/workflow.py
[2023-08-25T10:02:45.826+0000] {logging_mixin.py:150} INFO - [2023-08-25T10:02:45.820+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/workflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/workflow.py", line 1, in <module>
    from python_data_maker import pre_generate_log,generate_log,generate_item,generate_rating,generate_user
  File "/opt/airflow/dags/python_data_maker/pre_generate_log.py", line 1, in <module>
    from faker import Faker
ModuleNotFoundError: No module named 'faker'
[2023-08-25T10:02:45.828+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/workflow.py
[2023-08-25T10:02:45.897+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/workflow.py took 0.137 seconds
[2023-08-25T10:03:16.410+0000] {processor.py:157} INFO - Started process (PID=282) to work on /opt/airflow/dags/workflow.py
[2023-08-25T10:03:16.418+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/workflow.py for tasks to queue
[2023-08-25T10:03:16.421+0000] {logging_mixin.py:150} INFO - [2023-08-25T10:03:16.420+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/workflow.py
[2023-08-25T10:03:16.452+0000] {logging_mixin.py:150} INFO - [2023-08-25T10:03:16.446+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/workflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/workflow.py", line 1, in <module>
    from python_data_maker import pre_generate_log,generate_log,generate_item,generate_rating,generate_user
  File "/opt/airflow/dags/python_data_maker/pre_generate_log.py", line 1, in <module>
    from faker import Faker
ModuleNotFoundError: No module named 'faker'
[2023-08-25T10:03:16.454+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/workflow.py
[2023-08-25T10:03:16.517+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/workflow.py took 0.113 seconds
[2023-08-25T10:03:46.711+0000] {processor.py:157} INFO - Started process (PID=294) to work on /opt/airflow/dags/workflow.py
[2023-08-25T10:03:46.722+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/workflow.py for tasks to queue
[2023-08-25T10:03:46.731+0000] {logging_mixin.py:150} INFO - [2023-08-25T10:03:46.731+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/workflow.py
[2023-08-25T10:03:46.753+0000] {logging_mixin.py:150} INFO - [2023-08-25T10:03:46.749+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/workflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/workflow.py", line 1, in <module>
    from python_data_maker import pre_generate_log,generate_log,generate_item,generate_rating,generate_user
  File "/opt/airflow/dags/python_data_maker/pre_generate_log.py", line 1, in <module>
    from faker import Faker
ModuleNotFoundError: No module named 'faker'
[2023-08-25T10:03:46.754+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/workflow.py
[2023-08-25T10:03:46.804+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/workflow.py took 0.098 seconds
[2023-08-25T10:04:17.025+0000] {processor.py:157} INFO - Started process (PID=306) to work on /opt/airflow/dags/workflow.py
[2023-08-25T10:04:17.029+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/workflow.py for tasks to queue
[2023-08-25T10:04:17.034+0000] {logging_mixin.py:150} INFO - [2023-08-25T10:04:17.034+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/workflow.py
[2023-08-25T10:04:17.096+0000] {logging_mixin.py:150} INFO - [2023-08-25T10:04:17.083+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/workflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/workflow.py", line 1, in <module>
    from python_data_maker import pre_generate_log,generate_log,generate_item,generate_rating,generate_user
  File "/opt/airflow/dags/python_data_maker/pre_generate_log.py", line 1, in <module>
    from faker import Faker
ModuleNotFoundError: No module named 'faker'
[2023-08-25T10:04:17.120+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/workflow.py
[2023-08-25T10:04:17.202+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/workflow.py took 0.195 seconds
[2023-08-25T10:04:47.512+0000] {processor.py:157} INFO - Started process (PID=318) to work on /opt/airflow/dags/workflow.py
[2023-08-25T10:04:47.515+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/workflow.py for tasks to queue
[2023-08-25T10:04:47.520+0000] {logging_mixin.py:150} INFO - [2023-08-25T10:04:47.519+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/workflow.py
[2023-08-25T10:04:47.550+0000] {logging_mixin.py:150} INFO - [2023-08-25T10:04:47.544+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/workflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/workflow.py", line 1, in <module>
    from python_data_maker import pre_generate_log,generate_log,generate_item,generate_rating,generate_user
  File "/opt/airflow/dags/python_data_maker/pre_generate_log.py", line 1, in <module>
    from faker import Faker
ModuleNotFoundError: No module named 'faker'
[2023-08-25T10:04:47.552+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/workflow.py
[2023-08-25T10:04:47.602+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/workflow.py took 0.094 seconds
[2023-08-25T10:05:18.339+0000] {processor.py:157} INFO - Started process (PID=330) to work on /opt/airflow/dags/workflow.py
[2023-08-25T10:05:18.570+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/workflow.py for tasks to queue
[2023-08-25T10:05:18.581+0000] {logging_mixin.py:150} INFO - [2023-08-25T10:05:18.580+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/workflow.py
[2023-08-25T10:05:18.668+0000] {logging_mixin.py:150} INFO - [2023-08-25T10:05:18.660+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/workflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/workflow.py", line 1, in <module>
    from python_data_maker import pre_generate_log,generate_log,generate_item,generate_rating,generate_user
  File "/opt/airflow/dags/python_data_maker/pre_generate_log.py", line 1, in <module>
    from faker import Faker
ModuleNotFoundError: No module named 'faker'
[2023-08-25T10:05:18.671+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/workflow.py
[2023-08-25T10:05:18.766+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/workflow.py took 0.443 seconds
[2023-08-25T10:05:49.246+0000] {processor.py:157} INFO - Started process (PID=342) to work on /opt/airflow/dags/workflow.py
[2023-08-25T10:05:49.250+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/workflow.py for tasks to queue
[2023-08-25T10:05:49.255+0000] {logging_mixin.py:150} INFO - [2023-08-25T10:05:49.254+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/workflow.py
[2023-08-25T10:05:49.296+0000] {logging_mixin.py:150} INFO - [2023-08-25T10:05:49.289+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/workflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/workflow.py", line 1, in <module>
    from python_data_maker import pre_generate_log,generate_log,generate_item,generate_rating,generate_user
  File "/opt/airflow/dags/python_data_maker/pre_generate_log.py", line 1, in <module>
    from faker import Faker
ModuleNotFoundError: No module named 'faker'
[2023-08-25T10:05:49.299+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/workflow.py
[2023-08-25T10:05:49.351+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/workflow.py took 0.115 seconds
[2023-08-25T10:17:47.676+0000] {processor.py:157} INFO - Started process (PID=164) to work on /opt/airflow/dags/workflow.py
[2023-08-25T10:17:47.685+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/workflow.py for tasks to queue
[2023-08-25T10:17:47.689+0000] {logging_mixin.py:150} INFO - [2023-08-25T10:17:47.688+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/workflow.py
[2023-08-25T10:17:47.738+0000] {logging_mixin.py:150} INFO - [2023-08-25T10:17:47.732+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/workflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/workflow.py", line 1, in <module>
    from python_data_maker import pre_generate_log,generate_log,generate_item,generate_rating,generate_user
  File "/opt/airflow/dags/python_data_maker/pre_generate_log.py", line 1, in <module>
    from faker import Faker
ModuleNotFoundError: No module named 'faker'
[2023-08-25T10:17:47.741+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/workflow.py
[2023-08-25T10:17:47.785+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/workflow.py took 0.128 seconds
[2023-08-25T10:18:17.919+0000] {processor.py:157} INFO - Started process (PID=176) to work on /opt/airflow/dags/workflow.py
[2023-08-25T10:18:17.921+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/workflow.py for tasks to queue
[2023-08-25T10:18:17.924+0000] {logging_mixin.py:150} INFO - [2023-08-25T10:18:17.923+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/workflow.py
[2023-08-25T10:18:17.975+0000] {logging_mixin.py:150} INFO - [2023-08-25T10:18:17.968+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/workflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/workflow.py", line 1, in <module>
    from python_data_maker import pre_generate_log,generate_log,generate_item,generate_rating,generate_user
  File "/opt/airflow/dags/python_data_maker/pre_generate_log.py", line 1, in <module>
    from faker import Faker
ModuleNotFoundError: No module named 'faker'
[2023-08-25T10:18:17.978+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/workflow.py
[2023-08-25T10:18:18.021+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/workflow.py took 0.107 seconds
[2023-08-25T10:18:48.186+0000] {processor.py:157} INFO - Started process (PID=187) to work on /opt/airflow/dags/workflow.py
[2023-08-25T10:18:48.190+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/workflow.py for tasks to queue
[2023-08-25T10:18:48.193+0000] {logging_mixin.py:150} INFO - [2023-08-25T10:18:48.192+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/workflow.py
[2023-08-25T10:18:48.225+0000] {logging_mixin.py:150} INFO - [2023-08-25T10:18:48.220+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/workflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/workflow.py", line 1, in <module>
    from python_data_maker import pre_generate_log,generate_log,generate_item,generate_rating,generate_user
  File "/opt/airflow/dags/python_data_maker/pre_generate_log.py", line 1, in <module>
    from faker import Faker
ModuleNotFoundError: No module named 'faker'
[2023-08-25T10:18:48.227+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/workflow.py
[2023-08-25T10:18:48.263+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/workflow.py took 0.082 seconds
[2023-08-25T10:19:18.693+0000] {processor.py:157} INFO - Started process (PID=199) to work on /opt/airflow/dags/workflow.py
[2023-08-25T10:19:18.698+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/workflow.py for tasks to queue
[2023-08-25T10:19:18.709+0000] {logging_mixin.py:150} INFO - [2023-08-25T10:19:18.707+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/workflow.py
[2023-08-25T10:19:18.768+0000] {logging_mixin.py:150} INFO - [2023-08-25T10:19:18.761+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/workflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/workflow.py", line 1, in <module>
    from python_data_maker import pre_generate_log,generate_log,generate_item,generate_rating,generate_user
  File "/opt/airflow/dags/python_data_maker/pre_generate_log.py", line 1, in <module>
    from faker import Faker
ModuleNotFoundError: No module named 'faker'
[2023-08-25T10:19:18.775+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/workflow.py
[2023-08-25T10:19:18.822+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/workflow.py took 0.141 seconds
[2023-08-25T10:19:48.998+0000] {processor.py:157} INFO - Started process (PID=211) to work on /opt/airflow/dags/workflow.py
[2023-08-25T10:19:49.003+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/workflow.py for tasks to queue
[2023-08-25T10:19:49.006+0000] {logging_mixin.py:150} INFO - [2023-08-25T10:19:49.006+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/workflow.py
[2023-08-25T10:19:49.035+0000] {logging_mixin.py:150} INFO - [2023-08-25T10:19:49.027+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/workflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/workflow.py", line 1, in <module>
    from python_data_maker import pre_generate_log,generate_log,generate_item,generate_rating,generate_user
  File "/opt/airflow/dags/python_data_maker/pre_generate_log.py", line 1, in <module>
    from faker import Faker
ModuleNotFoundError: No module named 'faker'
[2023-08-25T10:19:49.038+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/workflow.py
[2023-08-25T10:19:49.083+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/workflow.py took 0.092 seconds
[2023-08-25T10:20:19.524+0000] {processor.py:157} INFO - Started process (PID=223) to work on /opt/airflow/dags/workflow.py
[2023-08-25T10:20:19.532+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/workflow.py for tasks to queue
[2023-08-25T10:20:19.537+0000] {logging_mixin.py:150} INFO - [2023-08-25T10:20:19.536+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/workflow.py
[2023-08-25T10:20:19.592+0000] {logging_mixin.py:150} INFO - [2023-08-25T10:20:19.582+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/workflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/workflow.py", line 1, in <module>
    from python_data_maker import pre_generate_log,generate_log,generate_item,generate_rating,generate_user
  File "/opt/airflow/dags/python_data_maker/pre_generate_log.py", line 1, in <module>
    from faker import Faker
ModuleNotFoundError: No module named 'faker'
[2023-08-25T10:20:19.598+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/workflow.py
[2023-08-25T10:20:19.678+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/workflow.py took 0.162 seconds
[2023-08-25T10:20:49.804+0000] {processor.py:157} INFO - Started process (PID=235) to work on /opt/airflow/dags/workflow.py
[2023-08-25T10:20:49.808+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/workflow.py for tasks to queue
[2023-08-25T10:20:49.811+0000] {logging_mixin.py:150} INFO - [2023-08-25T10:20:49.811+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/workflow.py
[2023-08-25T10:20:49.838+0000] {logging_mixin.py:150} INFO - [2023-08-25T10:20:49.833+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/workflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/workflow.py", line 1, in <module>
    from python_data_maker import pre_generate_log,generate_log,generate_item,generate_rating,generate_user
  File "/opt/airflow/dags/python_data_maker/pre_generate_log.py", line 1, in <module>
    from faker import Faker
ModuleNotFoundError: No module named 'faker'
[2023-08-25T10:20:49.840+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/workflow.py
[2023-08-25T10:20:49.882+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/workflow.py took 0.082 seconds
[2023-08-25T10:21:20.125+0000] {processor.py:157} INFO - Started process (PID=247) to work on /opt/airflow/dags/workflow.py
[2023-08-25T10:21:20.129+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/workflow.py for tasks to queue
[2023-08-25T10:21:20.133+0000] {logging_mixin.py:150} INFO - [2023-08-25T10:21:20.132+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/workflow.py
[2023-08-25T10:21:20.190+0000] {logging_mixin.py:150} INFO - [2023-08-25T10:21:20.182+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/workflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/workflow.py", line 1, in <module>
    from python_data_maker import pre_generate_log,generate_log,generate_item,generate_rating,generate_user
  File "/opt/airflow/dags/python_data_maker/pre_generate_log.py", line 1, in <module>
    from faker import Faker
ModuleNotFoundError: No module named 'faker'
[2023-08-25T10:21:20.196+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/workflow.py
[2023-08-25T10:21:20.302+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/workflow.py took 0.187 seconds
[2023-08-25T10:21:50.486+0000] {processor.py:157} INFO - Started process (PID=259) to work on /opt/airflow/dags/workflow.py
[2023-08-25T10:21:50.490+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/workflow.py for tasks to queue
[2023-08-25T10:21:50.494+0000] {logging_mixin.py:150} INFO - [2023-08-25T10:21:50.493+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/workflow.py
[2023-08-25T10:21:50.534+0000] {logging_mixin.py:150} INFO - [2023-08-25T10:21:50.526+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/workflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/workflow.py", line 1, in <module>
    from python_data_maker import pre_generate_log,generate_log,generate_item,generate_rating,generate_user
  File "/opt/airflow/dags/python_data_maker/pre_generate_log.py", line 1, in <module>
    from faker import Faker
ModuleNotFoundError: No module named 'faker'
[2023-08-25T10:21:50.541+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/workflow.py
[2023-08-25T10:21:50.610+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/workflow.py took 0.129 seconds
[2023-08-25T10:22:20.969+0000] {processor.py:157} INFO - Started process (PID=271) to work on /opt/airflow/dags/workflow.py
[2023-08-25T10:22:20.985+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/workflow.py for tasks to queue
[2023-08-25T10:22:20.994+0000] {logging_mixin.py:150} INFO - [2023-08-25T10:22:20.992+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/workflow.py
[2023-08-25T10:22:21.082+0000] {logging_mixin.py:150} INFO - [2023-08-25T10:22:21.068+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/workflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/workflow.py", line 1, in <module>
    from python_data_maker import pre_generate_log,generate_log,generate_item,generate_rating,generate_user
  File "/opt/airflow/dags/python_data_maker/pre_generate_log.py", line 1, in <module>
    from faker import Faker
ModuleNotFoundError: No module named 'faker'
[2023-08-25T10:22:21.084+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/workflow.py
[2023-08-25T10:22:21.185+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/workflow.py took 0.226 seconds
[2023-08-25T10:22:51.390+0000] {processor.py:157} INFO - Started process (PID=284) to work on /opt/airflow/dags/workflow.py
[2023-08-25T10:22:51.394+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/workflow.py for tasks to queue
[2023-08-25T10:22:51.398+0000] {logging_mixin.py:150} INFO - [2023-08-25T10:22:51.397+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/workflow.py
[2023-08-25T10:22:51.443+0000] {logging_mixin.py:150} INFO - [2023-08-25T10:22:51.435+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/workflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/workflow.py", line 1, in <module>
    from python_data_maker import pre_generate_log,generate_log,generate_item,generate_rating,generate_user
  File "/opt/airflow/dags/python_data_maker/pre_generate_log.py", line 1, in <module>
    from faker import Faker
ModuleNotFoundError: No module named 'faker'
[2023-08-25T10:22:51.447+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/workflow.py
[2023-08-25T10:22:51.503+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/workflow.py took 0.118 seconds
[2023-08-25T10:23:21.759+0000] {processor.py:157} INFO - Started process (PID=296) to work on /opt/airflow/dags/workflow.py
[2023-08-25T10:23:21.762+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/workflow.py for tasks to queue
[2023-08-25T10:23:21.766+0000] {logging_mixin.py:150} INFO - [2023-08-25T10:23:21.765+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/workflow.py
[2023-08-25T10:23:21.822+0000] {logging_mixin.py:150} INFO - [2023-08-25T10:23:21.808+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/workflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/workflow.py", line 1, in <module>
    from python_data_maker import pre_generate_log,generate_log,generate_item,generate_rating,generate_user
  File "/opt/airflow/dags/python_data_maker/pre_generate_log.py", line 1, in <module>
    from faker import Faker
ModuleNotFoundError: No module named 'faker'
[2023-08-25T10:23:21.830+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/workflow.py
[2023-08-25T10:23:21.878+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/workflow.py took 0.126 seconds
[2023-08-25T10:25:11.991+0000] {processor.py:157} INFO - Started process (PID=164) to work on /opt/airflow/dags/workflow.py
[2023-08-25T10:25:12.008+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/workflow.py for tasks to queue
[2023-08-25T10:25:12.018+0000] {logging_mixin.py:150} INFO - [2023-08-25T10:25:12.017+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/workflow.py
[2023-08-25T10:25:12.172+0000] {logging_mixin.py:150} INFO - [2023-08-25T10:25:12.148+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/workflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/workflow.py", line 1, in <module>
    from python_data_maker import pre_generate_log,generate_log,generate_item,generate_rating,generate_user
  File "/opt/airflow/dags/python_data_maker/pre_generate_log.py", line 1, in <module>
    from faker import Faker
ModuleNotFoundError: No module named 'faker'
[2023-08-25T10:25:12.182+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/workflow.py
[2023-08-25T10:25:12.373+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/workflow.py took 0.455 seconds
[2023-08-25T10:25:42.948+0000] {processor.py:157} INFO - Started process (PID=175) to work on /opt/airflow/dags/workflow.py
[2023-08-25T10:25:42.953+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/workflow.py for tasks to queue
[2023-08-25T10:25:42.961+0000] {logging_mixin.py:150} INFO - [2023-08-25T10:25:42.955+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/workflow.py
[2023-08-25T10:25:43.450+0000] {logging_mixin.py:150} INFO - [2023-08-25T10:25:43.208+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/workflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/workflow.py", line 1, in <module>
    from python_data_maker import pre_generate_log,generate_log,generate_item,generate_rating,generate_user
  File "/opt/airflow/dags/python_data_maker/pre_generate_log.py", line 1, in <module>
    from faker import Faker
ModuleNotFoundError: No module named 'faker'
[2023-08-25T10:25:43.454+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/workflow.py
[2023-08-25T10:25:43.644+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/workflow.py took 0.723 seconds
[2023-08-25T10:26:14.270+0000] {processor.py:157} INFO - Started process (PID=186) to work on /opt/airflow/dags/workflow.py
[2023-08-25T10:26:14.282+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/workflow.py for tasks to queue
[2023-08-25T10:26:14.305+0000] {logging_mixin.py:150} INFO - [2023-08-25T10:26:14.292+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/workflow.py
[2023-08-25T10:26:14.401+0000] {logging_mixin.py:150} INFO - [2023-08-25T10:26:14.379+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/workflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/workflow.py", line 1, in <module>
    from python_data_maker import pre_generate_log,generate_log,generate_item,generate_rating,generate_user
  File "/opt/airflow/dags/python_data_maker/pre_generate_log.py", line 1, in <module>
    from faker import Faker
ModuleNotFoundError: No module named 'faker'
[2023-08-25T10:26:14.406+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/workflow.py
[2023-08-25T10:26:14.645+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/workflow.py took 0.420 seconds
[2023-08-25T10:26:45.066+0000] {processor.py:157} INFO - Started process (PID=198) to work on /opt/airflow/dags/workflow.py
[2023-08-25T10:26:45.073+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/workflow.py for tasks to queue
[2023-08-25T10:26:45.088+0000] {logging_mixin.py:150} INFO - [2023-08-25T10:26:45.084+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/workflow.py
[2023-08-25T10:26:45.171+0000] {logging_mixin.py:150} INFO - [2023-08-25T10:26:45.152+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/workflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/workflow.py", line 1, in <module>
    from python_data_maker import pre_generate_log,generate_log,generate_item,generate_rating,generate_user
  File "/opt/airflow/dags/python_data_maker/pre_generate_log.py", line 1, in <module>
    from faker import Faker
ModuleNotFoundError: No module named 'faker'
[2023-08-25T10:26:45.178+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/workflow.py
[2023-08-25T10:26:45.274+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/workflow.py took 0.240 seconds
[2023-08-25T10:27:15.523+0000] {processor.py:157} INFO - Started process (PID=209) to work on /opt/airflow/dags/workflow.py
[2023-08-25T10:27:15.532+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/workflow.py for tasks to queue
[2023-08-25T10:27:15.537+0000] {logging_mixin.py:150} INFO - [2023-08-25T10:27:15.537+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/workflow.py
[2023-08-25T10:27:15.569+0000] {logging_mixin.py:150} INFO - [2023-08-25T10:27:15.560+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/workflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/workflow.py", line 1, in <module>
    from python_data_maker import pre_generate_log,generate_log,generate_item,generate_rating,generate_user
  File "/opt/airflow/dags/python_data_maker/pre_generate_log.py", line 1, in <module>
    from faker import Faker
ModuleNotFoundError: No module named 'faker'
[2023-08-25T10:27:15.571+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/workflow.py
[2023-08-25T10:27:15.621+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/workflow.py took 0.106 seconds
[2023-08-25T10:27:45.706+0000] {processor.py:157} INFO - Started process (PID=221) to work on /opt/airflow/dags/workflow.py
[2023-08-25T10:27:45.711+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/workflow.py for tasks to queue
[2023-08-25T10:27:45.715+0000] {logging_mixin.py:150} INFO - [2023-08-25T10:27:45.714+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/workflow.py
[2023-08-25T10:27:45.743+0000] {logging_mixin.py:150} INFO - [2023-08-25T10:27:45.737+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/workflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/workflow.py", line 1, in <module>
    from python_data_maker import pre_generate_log,generate_log,generate_item,generate_rating,generate_user
  File "/opt/airflow/dags/python_data_maker/pre_generate_log.py", line 1, in <module>
    from faker import Faker
ModuleNotFoundError: No module named 'faker'
[2023-08-25T10:27:45.747+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/workflow.py
[2023-08-25T10:27:45.803+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/workflow.py took 0.105 seconds
[2023-08-25T10:28:16.023+0000] {processor.py:157} INFO - Started process (PID=234) to work on /opt/airflow/dags/workflow.py
[2023-08-25T10:28:16.034+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/workflow.py for tasks to queue
[2023-08-25T10:28:16.037+0000] {logging_mixin.py:150} INFO - [2023-08-25T10:28:16.037+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/workflow.py
[2023-08-25T10:28:16.072+0000] {logging_mixin.py:150} INFO - [2023-08-25T10:28:16.065+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/workflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/workflow.py", line 1, in <module>
    from python_data_maker import pre_generate_log,generate_log,generate_item,generate_rating,generate_user
  File "/opt/airflow/dags/python_data_maker/pre_generate_log.py", line 1, in <module>
    from faker import Faker
ModuleNotFoundError: No module named 'faker'
[2023-08-25T10:28:16.075+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/workflow.py
[2023-08-25T10:28:16.134+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/workflow.py took 0.127 seconds
[2023-08-25T10:28:46.466+0000] {processor.py:157} INFO - Started process (PID=247) to work on /opt/airflow/dags/workflow.py
[2023-08-25T10:28:46.470+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/workflow.py for tasks to queue
[2023-08-25T10:28:46.477+0000] {logging_mixin.py:150} INFO - [2023-08-25T10:28:46.476+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/workflow.py
[2023-08-25T10:28:46.519+0000] {logging_mixin.py:150} INFO - [2023-08-25T10:28:46.514+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/workflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/workflow.py", line 1, in <module>
    from python_data_maker import pre_generate_log,generate_log,generate_item,generate_rating,generate_user
  File "/opt/airflow/dags/python_data_maker/pre_generate_log.py", line 1, in <module>
    from faker import Faker
ModuleNotFoundError: No module named 'faker'
[2023-08-25T10:28:46.521+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/workflow.py
[2023-08-25T10:28:46.576+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/workflow.py took 0.140 seconds
[2023-08-25T10:29:16.802+0000] {processor.py:157} INFO - Started process (PID=258) to work on /opt/airflow/dags/workflow.py
[2023-08-25T10:29:16.810+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/workflow.py for tasks to queue
[2023-08-25T10:29:16.815+0000] {logging_mixin.py:150} INFO - [2023-08-25T10:29:16.814+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/workflow.py
[2023-08-25T10:29:16.850+0000] {logging_mixin.py:150} INFO - [2023-08-25T10:29:16.843+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/workflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/workflow.py", line 1, in <module>
    from python_data_maker import pre_generate_log,generate_log,generate_item,generate_rating,generate_user
  File "/opt/airflow/dags/python_data_maker/pre_generate_log.py", line 1, in <module>
    from faker import Faker
ModuleNotFoundError: No module named 'faker'
[2023-08-25T10:29:16.852+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/workflow.py
[2023-08-25T10:29:16.915+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/workflow.py took 0.121 seconds
[2023-08-25T10:29:47.113+0000] {processor.py:157} INFO - Started process (PID=269) to work on /opt/airflow/dags/workflow.py
[2023-08-25T10:29:47.119+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/workflow.py for tasks to queue
[2023-08-25T10:29:47.122+0000] {logging_mixin.py:150} INFO - [2023-08-25T10:29:47.122+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/workflow.py
[2023-08-25T10:29:47.150+0000] {logging_mixin.py:150} INFO - [2023-08-25T10:29:47.145+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/workflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/workflow.py", line 1, in <module>
    from python_data_maker import pre_generate_log,generate_log,generate_item,generate_rating,generate_user
  File "/opt/airflow/dags/python_data_maker/pre_generate_log.py", line 1, in <module>
    from faker import Faker
ModuleNotFoundError: No module named 'faker'
[2023-08-25T10:29:47.152+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/workflow.py
[2023-08-25T10:29:47.192+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/workflow.py took 0.086 seconds
[2023-08-25T10:30:17.450+0000] {processor.py:157} INFO - Started process (PID=280) to work on /opt/airflow/dags/workflow.py
[2023-08-25T10:30:17.456+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/workflow.py for tasks to queue
[2023-08-25T10:30:17.460+0000] {logging_mixin.py:150} INFO - [2023-08-25T10:30:17.459+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/workflow.py
[2023-08-25T10:30:17.504+0000] {logging_mixin.py:150} INFO - [2023-08-25T10:30:17.498+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/workflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/workflow.py", line 1, in <module>
    from python_data_maker import pre_generate_log,generate_log,generate_item,generate_rating,generate_user
  File "/opt/airflow/dags/python_data_maker/pre_generate_log.py", line 1, in <module>
    from faker import Faker
ModuleNotFoundError: No module named 'faker'
[2023-08-25T10:30:17.507+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/workflow.py
[2023-08-25T10:30:17.553+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/workflow.py took 0.116 seconds
[2023-08-25T10:30:47.698+0000] {processor.py:157} INFO - Started process (PID=292) to work on /opt/airflow/dags/workflow.py
[2023-08-25T10:30:47.707+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/workflow.py for tasks to queue
[2023-08-25T10:30:47.729+0000] {logging_mixin.py:150} INFO - [2023-08-25T10:30:47.713+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/workflow.py
[2023-08-25T10:30:47.832+0000] {logging_mixin.py:150} INFO - [2023-08-25T10:30:47.819+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/workflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/workflow.py", line 1, in <module>
    from python_data_maker import pre_generate_log,generate_log,generate_item,generate_rating,generate_user
  File "/opt/airflow/dags/python_data_maker/pre_generate_log.py", line 1, in <module>
    from faker import Faker
ModuleNotFoundError: No module named 'faker'
[2023-08-25T10:30:47.848+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/workflow.py
[2023-08-25T10:30:47.978+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/workflow.py took 0.300 seconds
[2023-08-25T10:32:40.162+0000] {processor.py:157} INFO - Started process (PID=164) to work on /opt/airflow/dags/workflow.py
[2023-08-25T10:32:40.177+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/workflow.py for tasks to queue
[2023-08-25T10:32:40.187+0000] {logging_mixin.py:150} INFO - [2023-08-25T10:32:40.186+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/workflow.py
[2023-08-25T10:32:40.242+0000] {logging_mixin.py:150} INFO - [2023-08-25T10:32:40.231+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/workflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/workflow.py", line 1, in <module>
    from python_data_maker import pre_generate_log,generate_log,generate_item,generate_rating,generate_user
  File "/opt/airflow/dags/python_data_maker/pre_generate_log.py", line 1, in <module>
    from faker import Faker
ModuleNotFoundError: No module named 'faker'
[2023-08-25T10:32:40.247+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/workflow.py
[2023-08-25T10:32:40.368+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/workflow.py took 0.232 seconds
[2023-08-25T10:33:11.200+0000] {processor.py:157} INFO - Started process (PID=176) to work on /opt/airflow/dags/workflow.py
[2023-08-25T10:33:11.212+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/workflow.py for tasks to queue
[2023-08-25T10:33:11.218+0000] {logging_mixin.py:150} INFO - [2023-08-25T10:33:11.217+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/workflow.py
[2023-08-25T10:33:11.269+0000] {logging_mixin.py:150} INFO - [2023-08-25T10:33:11.254+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/workflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/workflow.py", line 1, in <module>
    from python_data_maker import pre_generate_log,generate_log,generate_item,generate_rating,generate_user
  File "/opt/airflow/dags/python_data_maker/pre_generate_log.py", line 1, in <module>
    from faker import Faker
ModuleNotFoundError: No module named 'faker'
[2023-08-25T10:33:11.275+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/workflow.py
[2023-08-25T10:33:11.352+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/workflow.py took 0.158 seconds
[2023-08-25T10:33:41.959+0000] {processor.py:157} INFO - Started process (PID=188) to work on /opt/airflow/dags/workflow.py
[2023-08-25T10:33:41.963+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/workflow.py for tasks to queue
[2023-08-25T10:33:41.967+0000] {logging_mixin.py:150} INFO - [2023-08-25T10:33:41.966+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/workflow.py
[2023-08-25T10:33:42.023+0000] {logging_mixin.py:150} INFO - [2023-08-25T10:33:42.013+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/workflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/workflow.py", line 1, in <module>
    from python_data_maker import pre_generate_log,generate_log,generate_item,generate_rating,generate_user
  File "/opt/airflow/dags/python_data_maker/pre_generate_log.py", line 1, in <module>
    from faker import Faker
ModuleNotFoundError: No module named 'faker'
[2023-08-25T10:33:42.027+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/workflow.py
[2023-08-25T10:33:42.090+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/workflow.py took 0.145 seconds
[2023-08-25T10:34:12.523+0000] {processor.py:157} INFO - Started process (PID=200) to work on /opt/airflow/dags/workflow.py
[2023-08-25T10:34:12.533+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/workflow.py for tasks to queue
[2023-08-25T10:34:12.550+0000] {logging_mixin.py:150} INFO - [2023-08-25T10:34:12.548+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/workflow.py
[2023-08-25T10:34:12.662+0000] {logging_mixin.py:150} INFO - [2023-08-25T10:34:12.653+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/workflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/workflow.py", line 1, in <module>
    from python_data_maker import pre_generate_log,generate_log,generate_item,generate_rating,generate_user
  File "/opt/airflow/dags/python_data_maker/pre_generate_log.py", line 1, in <module>
    from faker import Faker
ModuleNotFoundError: No module named 'faker'
[2023-08-25T10:34:12.668+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/workflow.py
[2023-08-25T10:34:12.797+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/workflow.py took 0.299 seconds
[2023-08-25T10:34:43.255+0000] {processor.py:157} INFO - Started process (PID=212) to work on /opt/airflow/dags/workflow.py
[2023-08-25T10:34:43.266+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/workflow.py for tasks to queue
[2023-08-25T10:34:43.273+0000] {logging_mixin.py:150} INFO - [2023-08-25T10:34:43.272+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/workflow.py
[2023-08-25T10:34:43.308+0000] {logging_mixin.py:150} INFO - [2023-08-25T10:34:43.299+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/workflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/workflow.py", line 1, in <module>
    from python_data_maker import pre_generate_log,generate_log,generate_item,generate_rating,generate_user
  File "/opt/airflow/dags/python_data_maker/pre_generate_log.py", line 1, in <module>
    from faker import Faker
ModuleNotFoundError: No module named 'faker'
[2023-08-25T10:34:43.315+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/workflow.py
[2023-08-25T10:34:43.372+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/workflow.py took 0.124 seconds
[2023-08-25T10:35:13.576+0000] {processor.py:157} INFO - Started process (PID=223) to work on /opt/airflow/dags/workflow.py
[2023-08-25T10:35:13.583+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/workflow.py for tasks to queue
[2023-08-25T10:35:13.586+0000] {logging_mixin.py:150} INFO - [2023-08-25T10:35:13.586+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/workflow.py
[2023-08-25T10:35:13.614+0000] {logging_mixin.py:150} INFO - [2023-08-25T10:35:13.608+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/workflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/workflow.py", line 1, in <module>
    from python_data_maker import pre_generate_log,generate_log,generate_item,generate_rating,generate_user
  File "/opt/airflow/dags/python_data_maker/pre_generate_log.py", line 1, in <module>
    from faker import Faker
ModuleNotFoundError: No module named 'faker'
[2023-08-25T10:35:13.616+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/workflow.py
[2023-08-25T10:35:13.649+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/workflow.py took 0.080 seconds
[2023-08-25T10:35:43.764+0000] {processor.py:157} INFO - Started process (PID=235) to work on /opt/airflow/dags/workflow.py
[2023-08-25T10:35:43.769+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/workflow.py for tasks to queue
[2023-08-25T10:35:43.772+0000] {logging_mixin.py:150} INFO - [2023-08-25T10:35:43.771+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/workflow.py
[2023-08-25T10:35:43.821+0000] {logging_mixin.py:150} INFO - [2023-08-25T10:35:43.815+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/workflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/workflow.py", line 1, in <module>
    from python_data_maker import pre_generate_log,generate_log,generate_item,generate_rating,generate_user
  File "/opt/airflow/dags/python_data_maker/pre_generate_log.py", line 1, in <module>
    from faker import Faker
ModuleNotFoundError: No module named 'faker'
[2023-08-25T10:35:43.823+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/workflow.py
[2023-08-25T10:35:43.859+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/workflow.py took 0.102 seconds
[2023-08-25T10:36:14.008+0000] {processor.py:157} INFO - Started process (PID=247) to work on /opt/airflow/dags/workflow.py
[2023-08-25T10:36:14.015+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/workflow.py for tasks to queue
[2023-08-25T10:36:14.017+0000] {logging_mixin.py:150} INFO - [2023-08-25T10:36:14.016+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/workflow.py
[2023-08-25T10:36:14.053+0000] {logging_mixin.py:150} INFO - [2023-08-25T10:36:14.043+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/workflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/workflow.py", line 1, in <module>
    from python_data_maker import pre_generate_log,generate_log,generate_item,generate_rating,generate_user
  File "/opt/airflow/dags/python_data_maker/pre_generate_log.py", line 1, in <module>
    from faker import Faker
ModuleNotFoundError: No module named 'faker'
[2023-08-25T10:36:14.056+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/workflow.py
[2023-08-25T10:36:14.102+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/workflow.py took 0.099 seconds
[2023-08-25T10:36:44.242+0000] {processor.py:157} INFO - Started process (PID=259) to work on /opt/airflow/dags/workflow.py
[2023-08-25T10:36:44.247+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/workflow.py for tasks to queue
[2023-08-25T10:36:44.249+0000] {logging_mixin.py:150} INFO - [2023-08-25T10:36:44.249+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/workflow.py
[2023-08-25T10:36:44.291+0000] {logging_mixin.py:150} INFO - [2023-08-25T10:36:44.277+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/workflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/workflow.py", line 1, in <module>
    from python_data_maker import pre_generate_log,generate_log,generate_item,generate_rating,generate_user
  File "/opt/airflow/dags/python_data_maker/pre_generate_log.py", line 1, in <module>
    from faker import Faker
ModuleNotFoundError: No module named 'faker'
[2023-08-25T10:36:44.292+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/workflow.py
[2023-08-25T10:36:44.337+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/workflow.py took 0.110 seconds
[2023-08-25T10:37:14.418+0000] {processor.py:157} INFO - Started process (PID=271) to work on /opt/airflow/dags/workflow.py
[2023-08-25T10:37:14.427+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/workflow.py for tasks to queue
[2023-08-25T10:37:14.429+0000] {logging_mixin.py:150} INFO - [2023-08-25T10:37:14.429+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/workflow.py
[2023-08-25T10:37:14.465+0000] {logging_mixin.py:150} INFO - [2023-08-25T10:37:14.457+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/workflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/workflow.py", line 1, in <module>
    from python_data_maker import pre_generate_log,generate_log,generate_item,generate_rating,generate_user
  File "/opt/airflow/dags/python_data_maker/pre_generate_log.py", line 1, in <module>
    from faker import Faker
ModuleNotFoundError: No module named 'faker'
[2023-08-25T10:37:14.467+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/workflow.py
[2023-08-25T10:37:14.500+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/workflow.py took 0.088 seconds
[2023-08-25T10:37:44.948+0000] {processor.py:157} INFO - Started process (PID=283) to work on /opt/airflow/dags/workflow.py
[2023-08-25T10:37:44.952+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/workflow.py for tasks to queue
[2023-08-25T10:37:44.955+0000] {logging_mixin.py:150} INFO - [2023-08-25T10:37:44.955+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/workflow.py
[2023-08-25T10:37:44.980+0000] {logging_mixin.py:150} INFO - [2023-08-25T10:37:44.974+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/workflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/workflow.py", line 1, in <module>
    from python_data_maker import pre_generate_log,generate_log,generate_item,generate_rating,generate_user
  File "/opt/airflow/dags/python_data_maker/pre_generate_log.py", line 1, in <module>
    from faker import Faker
ModuleNotFoundError: No module named 'faker'
[2023-08-25T10:37:44.982+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/workflow.py
[2023-08-25T10:37:45.019+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/workflow.py took 0.077 seconds
[2023-08-25T10:38:15.120+0000] {processor.py:157} INFO - Started process (PID=295) to work on /opt/airflow/dags/workflow.py
[2023-08-25T10:38:15.129+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/workflow.py for tasks to queue
[2023-08-25T10:38:15.134+0000] {logging_mixin.py:150} INFO - [2023-08-25T10:38:15.133+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/workflow.py
[2023-08-25T10:38:15.180+0000] {logging_mixin.py:150} INFO - [2023-08-25T10:38:15.171+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/workflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/workflow.py", line 1, in <module>
    from python_data_maker import pre_generate_log,generate_log,generate_item,generate_rating,generate_user
  File "/opt/airflow/dags/python_data_maker/pre_generate_log.py", line 1, in <module>
    from faker import Faker
ModuleNotFoundError: No module named 'faker'
[2023-08-25T10:38:15.183+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/workflow.py
[2023-08-25T10:38:15.240+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/workflow.py took 0.133 seconds
[2023-08-25T10:38:45.614+0000] {processor.py:157} INFO - Started process (PID=306) to work on /opt/airflow/dags/workflow.py
[2023-08-25T10:38:45.618+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/workflow.py for tasks to queue
[2023-08-25T10:38:45.624+0000] {logging_mixin.py:150} INFO - [2023-08-25T10:38:45.620+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/workflow.py
[2023-08-25T10:38:45.662+0000] {logging_mixin.py:150} INFO - [2023-08-25T10:38:45.653+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/workflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/workflow.py", line 1, in <module>
    from python_data_maker import pre_generate_log,generate_log,generate_item,generate_rating,generate_user
  File "/opt/airflow/dags/python_data_maker/pre_generate_log.py", line 1, in <module>
    from faker import Faker
ModuleNotFoundError: No module named 'faker'
[2023-08-25T10:38:45.666+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/workflow.py
[2023-08-25T10:38:45.706+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/workflow.py took 0.108 seconds
[2023-08-25T10:39:43.968+0000] {processor.py:157} INFO - Started process (PID=163) to work on /opt/airflow/dags/workflow.py
[2023-08-25T10:39:43.980+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/workflow.py for tasks to queue
[2023-08-25T10:39:43.982+0000] {logging_mixin.py:150} INFO - [2023-08-25T10:39:43.982+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/workflow.py
[2023-08-25T10:39:44.013+0000] {logging_mixin.py:150} INFO - [2023-08-25T10:39:44.009+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/workflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/workflow.py", line 1, in <module>
    from python_data_maker import pre_generate_log,generate_log,generate_item,generate_rating,generate_user
  File "/opt/airflow/dags/python_data_maker/pre_generate_log.py", line 1, in <module>
    from faker import Faker
ModuleNotFoundError: No module named 'faker'
[2023-08-25T10:39:44.016+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/workflow.py
[2023-08-25T10:39:44.074+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/workflow.py took 0.128 seconds
[2023-08-25T10:40:14.939+0000] {processor.py:157} INFO - Started process (PID=176) to work on /opt/airflow/dags/workflow.py
[2023-08-25T10:40:14.943+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/workflow.py for tasks to queue
[2023-08-25T10:40:14.946+0000] {logging_mixin.py:150} INFO - [2023-08-25T10:40:14.945+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/workflow.py
[2023-08-25T10:40:14.996+0000] {logging_mixin.py:150} INFO - [2023-08-25T10:40:14.987+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/workflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/workflow.py", line 1, in <module>
    from python_data_maker import pre_generate_log,generate_log,generate_item,generate_rating,generate_user
  File "/opt/airflow/dags/python_data_maker/pre_generate_log.py", line 1, in <module>
    from faker import Faker
ModuleNotFoundError: No module named 'faker'
[2023-08-25T10:40:14.999+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/workflow.py
[2023-08-25T10:40:15.074+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/workflow.py took 0.152 seconds
[2023-08-25T10:40:45.158+0000] {processor.py:157} INFO - Started process (PID=188) to work on /opt/airflow/dags/workflow.py
[2023-08-25T10:40:45.160+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/workflow.py for tasks to queue
[2023-08-25T10:40:45.163+0000] {logging_mixin.py:150} INFO - [2023-08-25T10:40:45.162+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/workflow.py
[2023-08-25T10:40:45.194+0000] {logging_mixin.py:150} INFO - [2023-08-25T10:40:45.186+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/workflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/workflow.py", line 1, in <module>
    from python_data_maker import pre_generate_log,generate_log,generate_item,generate_rating,generate_user
  File "/opt/airflow/dags/python_data_maker/pre_generate_log.py", line 1, in <module>
    from faker import Faker
ModuleNotFoundError: No module named 'faker'
[2023-08-25T10:40:45.197+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/workflow.py
[2023-08-25T10:40:45.241+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/workflow.py took 0.093 seconds
[2023-08-25T10:41:15.421+0000] {processor.py:157} INFO - Started process (PID=200) to work on /opt/airflow/dags/workflow.py
[2023-08-25T10:41:15.425+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/workflow.py for tasks to queue
[2023-08-25T10:41:15.441+0000] {logging_mixin.py:150} INFO - [2023-08-25T10:41:15.440+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/workflow.py
[2023-08-25T10:41:15.485+0000] {logging_mixin.py:150} INFO - [2023-08-25T10:41:15.481+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/workflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/workflow.py", line 1, in <module>
    from python_data_maker import pre_generate_log,generate_log,generate_item,generate_rating,generate_user
  File "/opt/airflow/dags/python_data_maker/pre_generate_log.py", line 1, in <module>
    from faker import Faker
ModuleNotFoundError: No module named 'faker'
[2023-08-25T10:41:15.488+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/workflow.py
[2023-08-25T10:41:15.542+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/workflow.py took 0.134 seconds
[2023-08-25T10:41:45.760+0000] {processor.py:157} INFO - Started process (PID=211) to work on /opt/airflow/dags/workflow.py
[2023-08-25T10:41:45.763+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/workflow.py for tasks to queue
[2023-08-25T10:41:45.766+0000] {logging_mixin.py:150} INFO - [2023-08-25T10:41:45.765+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/workflow.py
[2023-08-25T10:41:45.787+0000] {logging_mixin.py:150} INFO - [2023-08-25T10:41:45.783+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/workflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/workflow.py", line 1, in <module>
    from python_data_maker import pre_generate_log,generate_log,generate_item,generate_rating,generate_user
  File "/opt/airflow/dags/python_data_maker/pre_generate_log.py", line 1, in <module>
    from faker import Faker
ModuleNotFoundError: No module named 'faker'
[2023-08-25T10:41:45.791+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/workflow.py
[2023-08-25T10:41:45.829+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/workflow.py took 0.074 seconds
[2023-08-25T10:42:16.007+0000] {processor.py:157} INFO - Started process (PID=222) to work on /opt/airflow/dags/workflow.py
[2023-08-25T10:42:16.012+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/workflow.py for tasks to queue
[2023-08-25T10:42:16.020+0000] {logging_mixin.py:150} INFO - [2023-08-25T10:42:16.019+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/workflow.py
[2023-08-25T10:42:16.062+0000] {logging_mixin.py:150} INFO - [2023-08-25T10:42:16.053+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/workflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/workflow.py", line 1, in <module>
    from python_data_maker import pre_generate_log,generate_log,generate_item,generate_rating,generate_user
  File "/opt/airflow/dags/python_data_maker/pre_generate_log.py", line 1, in <module>
    from faker import Faker
ModuleNotFoundError: No module named 'faker'
[2023-08-25T10:42:16.067+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/workflow.py
[2023-08-25T10:42:16.112+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/workflow.py took 0.119 seconds
[2023-08-25T10:42:46.201+0000] {processor.py:157} INFO - Started process (PID=233) to work on /opt/airflow/dags/workflow.py
[2023-08-25T10:42:46.206+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/workflow.py for tasks to queue
[2023-08-25T10:42:46.209+0000] {logging_mixin.py:150} INFO - [2023-08-25T10:42:46.208+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/workflow.py
[2023-08-25T10:42:46.252+0000] {logging_mixin.py:150} INFO - [2023-08-25T10:42:46.245+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/workflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/workflow.py", line 1, in <module>
    from python_data_maker import pre_generate_log,generate_log,generate_item,generate_rating,generate_user
  File "/opt/airflow/dags/python_data_maker/pre_generate_log.py", line 1, in <module>
    from faker import Faker
ModuleNotFoundError: No module named 'faker'
[2023-08-25T10:42:46.267+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/workflow.py
[2023-08-25T10:42:46.324+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/workflow.py took 0.128 seconds
[2023-08-25T10:43:16.718+0000] {processor.py:157} INFO - Started process (PID=245) to work on /opt/airflow/dags/workflow.py
[2023-08-25T10:43:16.725+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/workflow.py for tasks to queue
[2023-08-25T10:43:16.730+0000] {logging_mixin.py:150} INFO - [2023-08-25T10:43:16.729+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/workflow.py
[2023-08-25T10:43:16.821+0000] {logging_mixin.py:150} INFO - [2023-08-25T10:43:16.812+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/workflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/workflow.py", line 1, in <module>
    from python_data_maker import pre_generate_log,generate_log,generate_item,generate_rating,generate_user
  File "/opt/airflow/dags/python_data_maker/pre_generate_log.py", line 1, in <module>
    from faker import Faker
ModuleNotFoundError: No module named 'faker'
[2023-08-25T10:43:16.829+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/workflow.py
[2023-08-25T10:43:16.932+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/workflow.py took 0.256 seconds
[2023-08-25T10:43:47.419+0000] {processor.py:157} INFO - Started process (PID=257) to work on /opt/airflow/dags/workflow.py
[2023-08-25T10:43:47.423+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/workflow.py for tasks to queue
[2023-08-25T10:43:47.430+0000] {logging_mixin.py:150} INFO - [2023-08-25T10:43:47.429+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/workflow.py
[2023-08-25T10:43:47.484+0000] {logging_mixin.py:150} INFO - [2023-08-25T10:43:47.473+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/workflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/workflow.py", line 1, in <module>
    from python_data_maker import pre_generate_log,generate_log,generate_item,generate_rating,generate_user
  File "/opt/airflow/dags/python_data_maker/pre_generate_log.py", line 1, in <module>
    from faker import Faker
ModuleNotFoundError: No module named 'faker'
[2023-08-25T10:43:47.486+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/workflow.py
[2023-08-25T10:43:47.649+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/workflow.py took 0.245 seconds
[2023-08-25T10:44:17.988+0000] {processor.py:157} INFO - Started process (PID=269) to work on /opt/airflow/dags/workflow.py
[2023-08-25T10:44:17.993+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/workflow.py for tasks to queue
[2023-08-25T10:44:17.998+0000] {logging_mixin.py:150} INFO - [2023-08-25T10:44:17.997+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/workflow.py
[2023-08-25T10:44:18.034+0000] {logging_mixin.py:150} INFO - [2023-08-25T10:44:18.025+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/workflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/workflow.py", line 1, in <module>
    from python_data_maker import pre_generate_log,generate_log,generate_item,generate_rating,generate_user
  File "/opt/airflow/dags/python_data_maker/pre_generate_log.py", line 1, in <module>
    from faker import Faker
ModuleNotFoundError: No module named 'faker'
[2023-08-25T10:44:18.037+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/workflow.py
[2023-08-25T10:44:18.089+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/workflow.py took 0.107 seconds
[2023-08-25T10:44:48.338+0000] {processor.py:157} INFO - Started process (PID=280) to work on /opt/airflow/dags/workflow.py
[2023-08-25T10:44:48.355+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/workflow.py for tasks to queue
[2023-08-25T10:44:48.373+0000] {logging_mixin.py:150} INFO - [2023-08-25T10:44:48.367+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/workflow.py
[2023-08-25T10:44:48.476+0000] {logging_mixin.py:150} INFO - [2023-08-25T10:44:48.471+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/workflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/workflow.py", line 1, in <module>
    from python_data_maker import pre_generate_log,generate_log,generate_item,generate_rating,generate_user
  File "/opt/airflow/dags/python_data_maker/pre_generate_log.py", line 1, in <module>
    from faker import Faker
ModuleNotFoundError: No module named 'faker'
[2023-08-25T10:44:48.479+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/workflow.py
[2023-08-25T10:44:48.535+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/workflow.py took 0.208 seconds
[2023-08-25T10:45:18.893+0000] {processor.py:157} INFO - Started process (PID=291) to work on /opt/airflow/dags/workflow.py
[2023-08-25T10:45:18.896+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/workflow.py for tasks to queue
[2023-08-25T10:45:18.899+0000] {logging_mixin.py:150} INFO - [2023-08-25T10:45:18.898+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/workflow.py
[2023-08-25T10:45:18.928+0000] {logging_mixin.py:150} INFO - [2023-08-25T10:45:18.920+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/workflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/workflow.py", line 1, in <module>
    from python_data_maker import pre_generate_log,generate_log,generate_item,generate_rating,generate_user
  File "/opt/airflow/dags/python_data_maker/pre_generate_log.py", line 1, in <module>
    from faker import Faker
ModuleNotFoundError: No module named 'faker'
[2023-08-25T10:45:18.931+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/workflow.py
[2023-08-25T10:45:18.994+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/workflow.py took 0.108 seconds
[2023-08-25T10:45:49.201+0000] {processor.py:157} INFO - Started process (PID=303) to work on /opt/airflow/dags/workflow.py
[2023-08-25T10:45:49.214+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/workflow.py for tasks to queue
[2023-08-25T10:45:49.218+0000] {logging_mixin.py:150} INFO - [2023-08-25T10:45:49.218+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/workflow.py
[2023-08-25T10:45:49.253+0000] {logging_mixin.py:150} INFO - [2023-08-25T10:45:49.245+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/workflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/workflow.py", line 1, in <module>
    from python_data_maker import pre_generate_log,generate_log,generate_item,generate_rating,generate_user
  File "/opt/airflow/dags/python_data_maker/pre_generate_log.py", line 1, in <module>
    from faker import Faker
ModuleNotFoundError: No module named 'faker'
[2023-08-25T10:45:49.255+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/workflow.py
[2023-08-25T10:45:49.302+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/workflow.py took 0.110 seconds
[2023-08-25T10:46:19.374+0000] {processor.py:157} INFO - Started process (PID=314) to work on /opt/airflow/dags/workflow.py
[2023-08-25T10:46:19.381+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/workflow.py for tasks to queue
[2023-08-25T10:46:19.384+0000] {logging_mixin.py:150} INFO - [2023-08-25T10:46:19.383+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/workflow.py
[2023-08-25T10:46:19.410+0000] {logging_mixin.py:150} INFO - [2023-08-25T10:46:19.405+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/workflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/workflow.py", line 1, in <module>
    from python_data_maker import pre_generate_log,generate_log,generate_item,generate_rating,generate_user
  File "/opt/airflow/dags/python_data_maker/pre_generate_log.py", line 1, in <module>
    from faker import Faker
ModuleNotFoundError: No module named 'faker'
[2023-08-25T10:46:19.413+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/workflow.py
[2023-08-25T10:46:19.447+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/workflow.py took 0.077 seconds
[2023-08-25T10:46:50.036+0000] {processor.py:157} INFO - Started process (PID=326) to work on /opt/airflow/dags/workflow.py
[2023-08-25T10:46:50.039+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/workflow.py for tasks to queue
[2023-08-25T10:46:50.041+0000] {logging_mixin.py:150} INFO - [2023-08-25T10:46:50.041+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/workflow.py
[2023-08-25T10:46:50.066+0000] {logging_mixin.py:150} INFO - [2023-08-25T10:46:50.062+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/workflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/workflow.py", line 1, in <module>
    from python_data_maker import pre_generate_log,generate_log,generate_item,generate_rating,generate_user
  File "/opt/airflow/dags/python_data_maker/pre_generate_log.py", line 1, in <module>
    from faker import Faker
ModuleNotFoundError: No module named 'faker'
[2023-08-25T10:46:50.068+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/workflow.py
[2023-08-25T10:46:50.111+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/workflow.py took 0.082 seconds
[2023-08-25T10:47:20.203+0000] {processor.py:157} INFO - Started process (PID=338) to work on /opt/airflow/dags/workflow.py
[2023-08-25T10:47:20.207+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/workflow.py for tasks to queue
[2023-08-25T10:47:20.213+0000] {logging_mixin.py:150} INFO - [2023-08-25T10:47:20.210+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/workflow.py
[2023-08-25T10:47:20.251+0000] {logging_mixin.py:150} INFO - [2023-08-25T10:47:20.236+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/workflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/workflow.py", line 1, in <module>
    from python_data_maker import pre_generate_log,generate_log,generate_item,generate_rating,generate_user
  File "/opt/airflow/dags/python_data_maker/pre_generate_log.py", line 1, in <module>
    from faker import Faker
ModuleNotFoundError: No module named 'faker'
[2023-08-25T10:47:20.254+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/workflow.py
[2023-08-25T10:47:20.294+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/workflow.py took 0.100 seconds
[2023-08-25T10:47:50.504+0000] {processor.py:157} INFO - Started process (PID=350) to work on /opt/airflow/dags/workflow.py
[2023-08-25T10:47:50.513+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/workflow.py for tasks to queue
[2023-08-25T10:47:50.518+0000] {logging_mixin.py:150} INFO - [2023-08-25T10:47:50.516+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/workflow.py
[2023-08-25T10:47:50.561+0000] {logging_mixin.py:150} INFO - [2023-08-25T10:47:50.555+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/workflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/workflow.py", line 1, in <module>
    from python_data_maker import pre_generate_log,generate_log,generate_item,generate_rating,generate_user
  File "/opt/airflow/dags/python_data_maker/pre_generate_log.py", line 1, in <module>
    from faker import Faker
ModuleNotFoundError: No module named 'faker'
[2023-08-25T10:47:50.564+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/workflow.py
[2023-08-25T10:47:50.632+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/workflow.py took 0.135 seconds
[2023-08-25T10:48:20.824+0000] {processor.py:157} INFO - Started process (PID=362) to work on /opt/airflow/dags/workflow.py
[2023-08-25T10:48:20.832+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/workflow.py for tasks to queue
[2023-08-25T10:48:20.835+0000] {logging_mixin.py:150} INFO - [2023-08-25T10:48:20.835+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/workflow.py
[2023-08-25T10:48:20.869+0000] {logging_mixin.py:150} INFO - [2023-08-25T10:48:20.860+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/workflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/workflow.py", line 1, in <module>
    from python_data_maker import pre_generate_log,generate_log,generate_item,generate_rating,generate_user
  File "/opt/airflow/dags/python_data_maker/pre_generate_log.py", line 1, in <module>
    from faker import Faker
ModuleNotFoundError: No module named 'faker'
[2023-08-25T10:48:20.871+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/workflow.py
[2023-08-25T10:48:20.929+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/workflow.py took 0.117 seconds
[2023-08-25T10:48:51.168+0000] {processor.py:157} INFO - Started process (PID=373) to work on /opt/airflow/dags/workflow.py
[2023-08-25T10:48:51.176+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/workflow.py for tasks to queue
[2023-08-25T10:48:51.179+0000] {logging_mixin.py:150} INFO - [2023-08-25T10:48:51.178+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/workflow.py
[2023-08-25T10:48:51.204+0000] {logging_mixin.py:150} INFO - [2023-08-25T10:48:51.198+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/workflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/workflow.py", line 1, in <module>
    from python_data_maker import pre_generate_log,generate_log,generate_item,generate_rating,generate_user
  File "/opt/airflow/dags/python_data_maker/pre_generate_log.py", line 1, in <module>
    from faker import Faker
ModuleNotFoundError: No module named 'faker'
[2023-08-25T10:48:51.206+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/workflow.py
[2023-08-25T10:48:51.260+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/workflow.py took 0.103 seconds
[2023-08-25T10:49:21.445+0000] {processor.py:157} INFO - Started process (PID=385) to work on /opt/airflow/dags/workflow.py
[2023-08-25T10:49:21.454+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/workflow.py for tasks to queue
[2023-08-25T10:49:21.457+0000] {logging_mixin.py:150} INFO - [2023-08-25T10:49:21.457+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/workflow.py
[2023-08-25T10:49:21.483+0000] {logging_mixin.py:150} INFO - [2023-08-25T10:49:21.479+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/workflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/workflow.py", line 1, in <module>
    from python_data_maker import pre_generate_log,generate_log,generate_item,generate_rating,generate_user
  File "/opt/airflow/dags/python_data_maker/pre_generate_log.py", line 1, in <module>
    from faker import Faker
ModuleNotFoundError: No module named 'faker'
[2023-08-25T10:49:21.485+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/workflow.py
[2023-08-25T10:49:21.531+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/workflow.py took 0.102 seconds
[2023-08-25T10:49:52.177+0000] {processor.py:157} INFO - Started process (PID=396) to work on /opt/airflow/dags/workflow.py
[2023-08-25T10:49:52.185+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/workflow.py for tasks to queue
[2023-08-25T10:49:52.188+0000] {logging_mixin.py:150} INFO - [2023-08-25T10:49:52.187+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/workflow.py
[2023-08-25T10:49:52.225+0000] {logging_mixin.py:150} INFO - [2023-08-25T10:49:52.219+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/workflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/workflow.py", line 1, in <module>
    from python_data_maker import pre_generate_log,generate_log,generate_item,generate_rating,generate_user
  File "/opt/airflow/dags/python_data_maker/pre_generate_log.py", line 1, in <module>
    from faker import Faker
ModuleNotFoundError: No module named 'faker'
[2023-08-25T10:49:52.226+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/workflow.py
[2023-08-25T10:49:52.296+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/workflow.py took 0.136 seconds
[2023-08-25T10:50:22.488+0000] {processor.py:157} INFO - Started process (PID=409) to work on /opt/airflow/dags/workflow.py
[2023-08-25T10:50:22.498+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/workflow.py for tasks to queue
[2023-08-25T10:50:22.502+0000] {logging_mixin.py:150} INFO - [2023-08-25T10:50:22.501+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/workflow.py
[2023-08-25T10:50:22.534+0000] {logging_mixin.py:150} INFO - [2023-08-25T10:50:22.526+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/workflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/workflow.py", line 1, in <module>
    from python_data_maker import pre_generate_log,generate_log,generate_item,generate_rating,generate_user
  File "/opt/airflow/dags/python_data_maker/pre_generate_log.py", line 1, in <module>
    from faker import Faker
ModuleNotFoundError: No module named 'faker'
[2023-08-25T10:50:22.536+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/workflow.py
[2023-08-25T10:50:22.584+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/workflow.py took 0.102 seconds
[2023-08-25T10:50:52.738+0000] {processor.py:157} INFO - Started process (PID=421) to work on /opt/airflow/dags/workflow.py
[2023-08-25T10:50:52.746+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/workflow.py for tasks to queue
[2023-08-25T10:50:52.750+0000] {logging_mixin.py:150} INFO - [2023-08-25T10:50:52.750+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/workflow.py
[2023-08-25T10:50:52.788+0000] {logging_mixin.py:150} INFO - [2023-08-25T10:50:52.779+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/workflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/workflow.py", line 1, in <module>
    from python_data_maker import pre_generate_log,generate_log,generate_item,generate_rating,generate_user
  File "/opt/airflow/dags/python_data_maker/pre_generate_log.py", line 1, in <module>
    from faker import Faker
ModuleNotFoundError: No module named 'faker'
[2023-08-25T10:50:52.790+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/workflow.py
[2023-08-25T10:50:52.837+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/workflow.py took 0.104 seconds
[2023-08-25T10:51:22.926+0000] {processor.py:157} INFO - Started process (PID=432) to work on /opt/airflow/dags/workflow.py
[2023-08-25T10:51:22.930+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/workflow.py for tasks to queue
[2023-08-25T10:51:22.933+0000] {logging_mixin.py:150} INFO - [2023-08-25T10:51:22.933+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/workflow.py
[2023-08-25T10:51:22.961+0000] {logging_mixin.py:150} INFO - [2023-08-25T10:51:22.956+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/workflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/workflow.py", line 1, in <module>
    from python_data_maker import pre_generate_log,generate_log,generate_item,generate_rating,generate_user
  File "/opt/airflow/dags/python_data_maker/pre_generate_log.py", line 1, in <module>
    from faker import Faker
ModuleNotFoundError: No module named 'faker'
[2023-08-25T10:51:22.965+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/workflow.py
[2023-08-25T10:51:23.006+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/workflow.py took 0.086 seconds
[2023-08-25T10:51:53.397+0000] {processor.py:157} INFO - Started process (PID=444) to work on /opt/airflow/dags/workflow.py
[2023-08-25T10:51:53.405+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/workflow.py for tasks to queue
[2023-08-25T10:51:53.408+0000] {logging_mixin.py:150} INFO - [2023-08-25T10:51:53.408+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/workflow.py
[2023-08-25T10:51:53.444+0000] {logging_mixin.py:150} INFO - [2023-08-25T10:51:53.435+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/workflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/workflow.py", line 1, in <module>
    from python_data_maker import pre_generate_log,generate_log,generate_item,generate_rating,generate_user
  File "/opt/airflow/dags/python_data_maker/pre_generate_log.py", line 1, in <module>
    from faker import Faker
ModuleNotFoundError: No module named 'faker'
[2023-08-25T10:51:53.446+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/workflow.py
[2023-08-25T10:51:53.484+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/workflow.py took 0.096 seconds
[2023-08-25T10:52:23.546+0000] {processor.py:157} INFO - Started process (PID=455) to work on /opt/airflow/dags/workflow.py
[2023-08-25T10:52:23.549+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/workflow.py for tasks to queue
[2023-08-25T10:52:23.552+0000] {logging_mixin.py:150} INFO - [2023-08-25T10:52:23.551+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/workflow.py
[2023-08-25T10:52:23.578+0000] {logging_mixin.py:150} INFO - [2023-08-25T10:52:23.572+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/workflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/workflow.py", line 1, in <module>
    from python_data_maker import pre_generate_log,generate_log,generate_item,generate_rating,generate_user
  File "/opt/airflow/dags/python_data_maker/pre_generate_log.py", line 1, in <module>
    from faker import Faker
ModuleNotFoundError: No module named 'faker'
[2023-08-25T10:52:23.580+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/workflow.py
[2023-08-25T10:52:23.622+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/workflow.py took 0.081 seconds
[2023-08-25T10:52:53.804+0000] {processor.py:157} INFO - Started process (PID=468) to work on /opt/airflow/dags/workflow.py
[2023-08-25T10:52:53.812+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/workflow.py for tasks to queue
[2023-08-25T10:52:53.814+0000] {logging_mixin.py:150} INFO - [2023-08-25T10:52:53.814+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/workflow.py
[2023-08-25T10:52:53.841+0000] {logging_mixin.py:150} INFO - [2023-08-25T10:52:53.835+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/workflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/workflow.py", line 1, in <module>
    from python_data_maker import pre_generate_log,generate_log,generate_item,generate_rating,generate_user
  File "/opt/airflow/dags/python_data_maker/pre_generate_log.py", line 1, in <module>
    from faker import Faker
ModuleNotFoundError: No module named 'faker'
[2023-08-25T10:52:53.843+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/workflow.py
[2023-08-25T10:52:53.888+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/workflow.py took 0.094 seconds
[2023-08-25T10:53:23.956+0000] {processor.py:157} INFO - Started process (PID=480) to work on /opt/airflow/dags/workflow.py
[2023-08-25T10:53:23.965+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/workflow.py for tasks to queue
[2023-08-25T10:53:23.969+0000] {logging_mixin.py:150} INFO - [2023-08-25T10:53:23.968+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/workflow.py
[2023-08-25T10:53:23.999+0000] {logging_mixin.py:150} INFO - [2023-08-25T10:53:23.995+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/workflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/workflow.py", line 1, in <module>
    from python_data_maker import pre_generate_log,generate_log,generate_item,generate_rating,generate_user
  File "/opt/airflow/dags/python_data_maker/pre_generate_log.py", line 1, in <module>
    from faker import Faker
ModuleNotFoundError: No module named 'faker'
[2023-08-25T10:53:24.002+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/workflow.py
[2023-08-25T10:53:24.058+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/workflow.py took 0.106 seconds
[2023-08-25T10:53:54.241+0000] {processor.py:157} INFO - Started process (PID=492) to work on /opt/airflow/dags/workflow.py
[2023-08-25T10:53:54.244+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/workflow.py for tasks to queue
[2023-08-25T10:53:54.247+0000] {logging_mixin.py:150} INFO - [2023-08-25T10:53:54.246+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/workflow.py
[2023-08-25T10:53:54.271+0000] {logging_mixin.py:150} INFO - [2023-08-25T10:53:54.266+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/workflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/workflow.py", line 1, in <module>
    from python_data_maker import pre_generate_log,generate_log,generate_item,generate_rating,generate_user
  File "/opt/airflow/dags/python_data_maker/pre_generate_log.py", line 1, in <module>
    from faker import Faker
ModuleNotFoundError: No module named 'faker'
[2023-08-25T10:53:54.273+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/workflow.py
[2023-08-25T10:53:54.305+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/workflow.py took 0.070 seconds
[2023-08-25T10:54:24.426+0000] {processor.py:157} INFO - Started process (PID=503) to work on /opt/airflow/dags/workflow.py
[2023-08-25T10:54:24.434+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/workflow.py for tasks to queue
[2023-08-25T10:54:24.437+0000] {logging_mixin.py:150} INFO - [2023-08-25T10:54:24.436+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/workflow.py
[2023-08-25T10:54:24.468+0000] {logging_mixin.py:150} INFO - [2023-08-25T10:54:24.463+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/workflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/workflow.py", line 1, in <module>
    from python_data_maker import pre_generate_log,generate_log,generate_item,generate_rating,generate_user
  File "/opt/airflow/dags/python_data_maker/pre_generate_log.py", line 1, in <module>
    from faker import Faker
ModuleNotFoundError: No module named 'faker'
[2023-08-25T10:54:24.470+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/workflow.py
[2023-08-25T10:54:24.510+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/workflow.py took 0.088 seconds
[2023-08-25T10:54:54.733+0000] {processor.py:157} INFO - Started process (PID=514) to work on /opt/airflow/dags/workflow.py
[2023-08-25T10:54:54.738+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/workflow.py for tasks to queue
[2023-08-25T10:54:54.742+0000] {logging_mixin.py:150} INFO - [2023-08-25T10:54:54.741+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/workflow.py
[2023-08-25T10:54:54.769+0000] {logging_mixin.py:150} INFO - [2023-08-25T10:54:54.763+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/workflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/workflow.py", line 1, in <module>
    from python_data_maker import pre_generate_log,generate_log,generate_item,generate_rating,generate_user
  File "/opt/airflow/dags/python_data_maker/pre_generate_log.py", line 1, in <module>
    from faker import Faker
ModuleNotFoundError: No module named 'faker'
[2023-08-25T10:54:54.773+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/workflow.py
[2023-08-25T10:54:54.819+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/workflow.py took 0.090 seconds
[2023-08-25T10:55:25.895+0000] {processor.py:157} INFO - Started process (PID=525) to work on /opt/airflow/dags/workflow.py
[2023-08-25T10:55:25.906+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/workflow.py for tasks to queue
[2023-08-25T10:55:25.915+0000] {logging_mixin.py:150} INFO - [2023-08-25T10:55:25.913+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/workflow.py
[2023-08-25T10:55:26.043+0000] {logging_mixin.py:150} INFO - [2023-08-25T10:55:26.012+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/workflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/workflow.py", line 1, in <module>
    from python_data_maker import pre_generate_log,generate_log,generate_item,generate_rating,generate_user
  File "/opt/airflow/dags/python_data_maker/pre_generate_log.py", line 1, in <module>
    from faker import Faker
ModuleNotFoundError: No module named 'faker'
[2023-08-25T10:55:26.045+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/workflow.py
[2023-08-25T10:55:26.141+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/workflow.py took 0.266 seconds
[2023-08-25T10:55:56.923+0000] {processor.py:157} INFO - Started process (PID=537) to work on /opt/airflow/dags/workflow.py
[2023-08-25T10:55:56.931+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/workflow.py for tasks to queue
[2023-08-25T10:55:56.937+0000] {logging_mixin.py:150} INFO - [2023-08-25T10:55:56.937+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/workflow.py
[2023-08-25T10:55:56.986+0000] {logging_mixin.py:150} INFO - [2023-08-25T10:55:56.981+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/workflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/workflow.py", line 1, in <module>
    from python_data_maker import pre_generate_log,generate_log,generate_item,generate_rating,generate_user
  File "/opt/airflow/dags/python_data_maker/pre_generate_log.py", line 1, in <module>
    from faker import Faker
ModuleNotFoundError: No module named 'faker'
[2023-08-25T10:55:56.990+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/workflow.py
[2023-08-25T10:55:57.039+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/workflow.py took 0.126 seconds
[2023-08-25T10:56:27.258+0000] {processor.py:157} INFO - Started process (PID=549) to work on /opt/airflow/dags/workflow.py
[2023-08-25T10:56:27.263+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/workflow.py for tasks to queue
[2023-08-25T10:56:27.267+0000] {logging_mixin.py:150} INFO - [2023-08-25T10:56:27.266+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/workflow.py
[2023-08-25T10:56:27.295+0000] {logging_mixin.py:150} INFO - [2023-08-25T10:56:27.290+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/workflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/workflow.py", line 1, in <module>
    from python_data_maker import pre_generate_log,generate_log,generate_item,generate_rating,generate_user
  File "/opt/airflow/dags/python_data_maker/pre_generate_log.py", line 1, in <module>
    from faker import Faker
ModuleNotFoundError: No module named 'faker'
[2023-08-25T10:56:27.297+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/workflow.py
[2023-08-25T10:56:27.344+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/workflow.py took 0.096 seconds
[2023-08-25T10:56:57.400+0000] {processor.py:157} INFO - Started process (PID=560) to work on /opt/airflow/dags/workflow.py
[2023-08-25T10:56:57.408+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/workflow.py for tasks to queue
[2023-08-25T10:56:57.411+0000] {logging_mixin.py:150} INFO - [2023-08-25T10:56:57.411+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/workflow.py
[2023-08-25T10:56:57.441+0000] {logging_mixin.py:150} INFO - [2023-08-25T10:56:57.435+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/workflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/workflow.py", line 1, in <module>
    from python_data_maker import pre_generate_log,generate_log,generate_item,generate_rating,generate_user
  File "/opt/airflow/dags/python_data_maker/pre_generate_log.py", line 1, in <module>
    from faker import Faker
ModuleNotFoundError: No module named 'faker'
[2023-08-25T10:56:57.443+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/workflow.py
[2023-08-25T10:56:57.482+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/workflow.py took 0.089 seconds
[2023-08-25T10:57:27.648+0000] {processor.py:157} INFO - Started process (PID=571) to work on /opt/airflow/dags/workflow.py
[2023-08-25T10:57:27.656+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/workflow.py for tasks to queue
[2023-08-25T10:57:27.659+0000] {logging_mixin.py:150} INFO - [2023-08-25T10:57:27.658+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/workflow.py
[2023-08-25T10:57:27.691+0000] {logging_mixin.py:150} INFO - [2023-08-25T10:57:27.684+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/workflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/workflow.py", line 1, in <module>
    from python_data_maker import pre_generate_log,generate_log,generate_item,generate_rating,generate_user
  File "/opt/airflow/dags/python_data_maker/pre_generate_log.py", line 1, in <module>
    from faker import Faker
ModuleNotFoundError: No module named 'faker'
[2023-08-25T10:57:27.693+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/workflow.py
[2023-08-25T10:57:27.739+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/workflow.py took 0.098 seconds
[2023-08-25T10:57:59.130+0000] {processor.py:157} INFO - Started process (PID=583) to work on /opt/airflow/dags/workflow.py
[2023-08-25T10:57:59.143+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/workflow.py for tasks to queue
[2023-08-25T10:57:59.149+0000] {logging_mixin.py:150} INFO - [2023-08-25T10:57:59.148+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/workflow.py
[2023-08-25T10:57:59.267+0000] {logging_mixin.py:150} INFO - [2023-08-25T10:57:59.230+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/workflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/workflow.py", line 1, in <module>
    from python_data_maker import pre_generate_log,generate_log,generate_item,generate_rating,generate_user
  File "/opt/airflow/dags/python_data_maker/pre_generate_log.py", line 1, in <module>
    from faker import Faker
ModuleNotFoundError: No module named 'faker'
[2023-08-25T10:57:59.274+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/workflow.py
[2023-08-25T10:57:59.360+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/workflow.py took 0.396 seconds
[2023-08-25T11:05:20.444+0000] {processor.py:157} INFO - Started process (PID=600) to work on /opt/airflow/dags/workflow.py
[2023-08-25T11:05:20.461+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/workflow.py for tasks to queue
[2023-08-25T11:05:20.475+0000] {logging_mixin.py:150} INFO - [2023-08-25T11:05:20.474+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/workflow.py
[2023-08-25T11:05:20.531+0000] {logging_mixin.py:150} INFO - [2023-08-25T11:05:20.521+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/workflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/workflow.py", line 1, in <module>
    from python_data_maker import pre_generate_log,generate_log,generate_item,generate_rating,generate_user
  File "/opt/airflow/dags/python_data_maker/pre_generate_log.py", line 1, in <module>
    from faker import Faker
ModuleNotFoundError: No module named 'faker'
[2023-08-25T11:05:20.535+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/workflow.py
[2023-08-25T11:05:20.590+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/workflow.py took 0.162 seconds
[2023-08-25T11:05:51.553+0000] {processor.py:157} INFO - Started process (PID=612) to work on /opt/airflow/dags/workflow.py
[2023-08-25T11:05:51.562+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/workflow.py for tasks to queue
[2023-08-25T11:05:51.570+0000] {logging_mixin.py:150} INFO - [2023-08-25T11:05:51.567+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/workflow.py
[2023-08-25T11:05:51.658+0000] {logging_mixin.py:150} INFO - [2023-08-25T11:05:51.634+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/workflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/workflow.py", line 1, in <module>
    from python_data_maker import pre_generate_log,generate_log,generate_item,generate_rating,generate_user
  File "/opt/airflow/dags/python_data_maker/pre_generate_log.py", line 1, in <module>
    from faker import Faker
ModuleNotFoundError: No module named 'faker'
[2023-08-25T11:05:51.697+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/workflow.py
[2023-08-25T11:05:51.773+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/workflow.py took 0.233 seconds
[2023-08-25T11:06:22.059+0000] {processor.py:157} INFO - Started process (PID=624) to work on /opt/airflow/dags/workflow.py
[2023-08-25T11:06:22.064+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/workflow.py for tasks to queue
[2023-08-25T11:06:22.067+0000] {logging_mixin.py:150} INFO - [2023-08-25T11:06:22.066+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/workflow.py
[2023-08-25T11:06:22.092+0000] {logging_mixin.py:150} INFO - [2023-08-25T11:06:22.087+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/workflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/workflow.py", line 1, in <module>
    from python_data_maker import pre_generate_log,generate_log,generate_item,generate_rating,generate_user
  File "/opt/airflow/dags/python_data_maker/pre_generate_log.py", line 1, in <module>
    from faker import Faker
ModuleNotFoundError: No module named 'faker'
[2023-08-25T11:06:22.094+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/workflow.py
[2023-08-25T11:06:22.131+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/workflow.py took 0.079 seconds
[2023-08-25T11:06:52.469+0000] {processor.py:157} INFO - Started process (PID=636) to work on /opt/airflow/dags/workflow.py
[2023-08-25T11:06:52.471+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/workflow.py for tasks to queue
[2023-08-25T11:06:52.479+0000] {logging_mixin.py:150} INFO - [2023-08-25T11:06:52.478+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/workflow.py
[2023-08-25T11:06:52.518+0000] {logging_mixin.py:150} INFO - [2023-08-25T11:06:52.513+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/workflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/workflow.py", line 1, in <module>
    from python_data_maker import pre_generate_log,generate_log,generate_item,generate_rating,generate_user
  File "/opt/airflow/dags/python_data_maker/pre_generate_log.py", line 1, in <module>
    from faker import Faker
ModuleNotFoundError: No module named 'faker'
[2023-08-25T11:06:52.520+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/workflow.py
[2023-08-25T11:06:52.622+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/workflow.py took 0.161 seconds
[2023-08-25T11:07:23.093+0000] {processor.py:157} INFO - Started process (PID=648) to work on /opt/airflow/dags/workflow.py
[2023-08-25T11:07:23.105+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/workflow.py for tasks to queue
[2023-08-25T11:07:23.110+0000] {logging_mixin.py:150} INFO - [2023-08-25T11:07:23.109+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/workflow.py
[2023-08-25T11:07:23.202+0000] {logging_mixin.py:150} INFO - [2023-08-25T11:07:23.182+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/workflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/workflow.py", line 1, in <module>
    from python_data_maker import pre_generate_log,generate_log,generate_item,generate_rating,generate_user
  File "/opt/airflow/dags/python_data_maker/pre_generate_log.py", line 1, in <module>
    from faker import Faker
ModuleNotFoundError: No module named 'faker'
[2023-08-25T11:07:23.205+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/workflow.py
[2023-08-25T11:07:23.307+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/workflow.py took 0.231 seconds
[2023-08-25T11:07:53.795+0000] {processor.py:157} INFO - Started process (PID=660) to work on /opt/airflow/dags/workflow.py
[2023-08-25T11:07:53.806+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/workflow.py for tasks to queue
[2023-08-25T11:07:53.808+0000] {logging_mixin.py:150} INFO - [2023-08-25T11:07:53.808+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/workflow.py
[2023-08-25T11:07:53.839+0000] {logging_mixin.py:150} INFO - [2023-08-25T11:07:53.833+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/workflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/workflow.py", line 1, in <module>
    from python_data_maker import pre_generate_log,generate_log,generate_item,generate_rating,generate_user
  File "/opt/airflow/dags/python_data_maker/pre_generate_log.py", line 1, in <module>
    from faker import Faker
ModuleNotFoundError: No module named 'faker'
[2023-08-25T11:07:53.841+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/workflow.py
[2023-08-25T11:07:53.896+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/workflow.py took 0.111 seconds
[2023-08-25T11:08:23.986+0000] {processor.py:157} INFO - Started process (PID=672) to work on /opt/airflow/dags/workflow.py
[2023-08-25T11:08:23.998+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/workflow.py for tasks to queue
[2023-08-25T11:08:24.000+0000] {logging_mixin.py:150} INFO - [2023-08-25T11:08:24.000+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/workflow.py
[2023-08-25T11:08:24.037+0000] {logging_mixin.py:150} INFO - [2023-08-25T11:08:24.025+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/workflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/workflow.py", line 1, in <module>
    from python_data_maker import pre_generate_log,generate_log,generate_item,generate_rating,generate_user
  File "/opt/airflow/dags/python_data_maker/pre_generate_log.py", line 1, in <module>
    from faker import Faker
ModuleNotFoundError: No module named 'faker'
[2023-08-25T11:08:24.040+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/workflow.py
[2023-08-25T11:08:24.100+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/workflow.py took 0.131 seconds
[2023-08-25T11:08:54.314+0000] {processor.py:157} INFO - Started process (PID=684) to work on /opt/airflow/dags/workflow.py
[2023-08-25T11:08:54.317+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/workflow.py for tasks to queue
[2023-08-25T11:08:54.320+0000] {logging_mixin.py:150} INFO - [2023-08-25T11:08:54.319+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/workflow.py
[2023-08-25T11:08:54.351+0000] {logging_mixin.py:150} INFO - [2023-08-25T11:08:54.344+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/workflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/workflow.py", line 1, in <module>
    from python_data_maker import pre_generate_log,generate_log,generate_item,generate_rating,generate_user
  File "/opt/airflow/dags/python_data_maker/pre_generate_log.py", line 1, in <module>
    from faker import Faker
ModuleNotFoundError: No module named 'faker'
[2023-08-25T11:08:54.353+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/workflow.py
[2023-08-25T11:08:54.405+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/workflow.py took 0.102 seconds
[2023-08-25T11:09:24.499+0000] {processor.py:157} INFO - Started process (PID=695) to work on /opt/airflow/dags/workflow.py
[2023-08-25T11:09:24.503+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/workflow.py for tasks to queue
[2023-08-25T11:09:24.506+0000] {logging_mixin.py:150} INFO - [2023-08-25T11:09:24.505+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/workflow.py
[2023-08-25T11:09:24.556+0000] {logging_mixin.py:150} INFO - [2023-08-25T11:09:24.537+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/workflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/workflow.py", line 1, in <module>
    from python_data_maker import pre_generate_log,generate_log,generate_item,generate_rating,generate_user
  File "/opt/airflow/dags/python_data_maker/pre_generate_log.py", line 1, in <module>
    from faker import Faker
ModuleNotFoundError: No module named 'faker'
[2023-08-25T11:09:24.559+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/workflow.py
[2023-08-25T11:09:24.598+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/workflow.py took 0.109 seconds
[2023-08-25T11:09:55.059+0000] {processor.py:157} INFO - Started process (PID=707) to work on /opt/airflow/dags/workflow.py
[2023-08-25T11:09:55.065+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/workflow.py for tasks to queue
[2023-08-25T11:09:55.070+0000] {logging_mixin.py:150} INFO - [2023-08-25T11:09:55.069+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/workflow.py
[2023-08-25T11:09:55.153+0000] {logging_mixin.py:150} INFO - [2023-08-25T11:09:55.140+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/workflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/workflow.py", line 1, in <module>
    from python_data_maker import pre_generate_log,generate_log,generate_item,generate_rating,generate_user
  File "/opt/airflow/dags/python_data_maker/pre_generate_log.py", line 1, in <module>
    from faker import Faker
ModuleNotFoundError: No module named 'faker'
[2023-08-25T11:09:55.155+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/workflow.py
[2023-08-25T11:09:55.202+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/workflow.py took 0.149 seconds
[2023-08-25T11:10:25.289+0000] {processor.py:157} INFO - Started process (PID=718) to work on /opt/airflow/dags/workflow.py
[2023-08-25T11:10:25.291+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/workflow.py for tasks to queue
[2023-08-25T11:10:25.295+0000] {logging_mixin.py:150} INFO - [2023-08-25T11:10:25.295+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/workflow.py
[2023-08-25T11:10:25.341+0000] {logging_mixin.py:150} INFO - [2023-08-25T11:10:25.336+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/workflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/workflow.py", line 1, in <module>
    from python_data_maker import pre_generate_log,generate_log,generate_item,generate_rating,generate_user
  File "/opt/airflow/dags/python_data_maker/pre_generate_log.py", line 1, in <module>
    from faker import Faker
ModuleNotFoundError: No module named 'faker'
[2023-08-25T11:10:25.343+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/workflow.py
[2023-08-25T11:10:25.391+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/workflow.py took 0.109 seconds
[2023-08-25T11:10:55.552+0000] {processor.py:157} INFO - Started process (PID=730) to work on /opt/airflow/dags/workflow.py
[2023-08-25T11:10:55.555+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/workflow.py for tasks to queue
[2023-08-25T11:10:55.563+0000] {logging_mixin.py:150} INFO - [2023-08-25T11:10:55.562+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/workflow.py
[2023-08-25T11:10:55.606+0000] {logging_mixin.py:150} INFO - [2023-08-25T11:10:55.595+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/workflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/workflow.py", line 1, in <module>
    from python_data_maker import pre_generate_log,generate_log,generate_item,generate_rating,generate_user
  File "/opt/airflow/dags/python_data_maker/pre_generate_log.py", line 1, in <module>
    from faker import Faker
ModuleNotFoundError: No module named 'faker'
[2023-08-25T11:10:55.610+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/workflow.py
[2023-08-25T11:10:55.669+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/workflow.py took 0.132 seconds
[2023-08-25T11:11:25.730+0000] {processor.py:157} INFO - Started process (PID=742) to work on /opt/airflow/dags/workflow.py
[2023-08-25T11:11:25.733+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/workflow.py for tasks to queue
[2023-08-25T11:11:25.735+0000] {logging_mixin.py:150} INFO - [2023-08-25T11:11:25.735+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/workflow.py
[2023-08-25T11:11:25.757+0000] {logging_mixin.py:150} INFO - [2023-08-25T11:11:25.751+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/workflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/workflow.py", line 1, in <module>
    from python_data_maker import pre_generate_log,generate_log,generate_item,generate_rating,generate_user
  File "/opt/airflow/dags/python_data_maker/pre_generate_log.py", line 1, in <module>
    from faker import Faker
ModuleNotFoundError: No module named 'faker'
[2023-08-25T11:11:25.759+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/workflow.py
[2023-08-25T11:11:25.802+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/workflow.py took 0.078 seconds
[2023-08-25T11:11:56.011+0000] {processor.py:157} INFO - Started process (PID=753) to work on /opt/airflow/dags/workflow.py
[2023-08-25T11:11:56.014+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/workflow.py for tasks to queue
[2023-08-25T11:11:56.017+0000] {logging_mixin.py:150} INFO - [2023-08-25T11:11:56.016+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/workflow.py
[2023-08-25T11:11:56.051+0000] {logging_mixin.py:150} INFO - [2023-08-25T11:11:56.041+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/workflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/workflow.py", line 1, in <module>
    from python_data_maker import pre_generate_log,generate_log,generate_item,generate_rating,generate_user
  File "/opt/airflow/dags/python_data_maker/pre_generate_log.py", line 1, in <module>
    from faker import Faker
ModuleNotFoundError: No module named 'faker'
[2023-08-25T11:11:56.055+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/workflow.py
[2023-08-25T11:11:56.107+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/workflow.py took 0.106 seconds
[2023-08-25T11:12:26.300+0000] {processor.py:157} INFO - Started process (PID=765) to work on /opt/airflow/dags/workflow.py
[2023-08-25T11:12:26.310+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/workflow.py for tasks to queue
[2023-08-25T11:12:26.313+0000] {logging_mixin.py:150} INFO - [2023-08-25T11:12:26.312+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/workflow.py
[2023-08-25T11:12:26.380+0000] {logging_mixin.py:150} INFO - [2023-08-25T11:12:26.373+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/workflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/workflow.py", line 1, in <module>
    from python_data_maker import pre_generate_log,generate_log,generate_item,generate_rating,generate_user
  File "/opt/airflow/dags/python_data_maker/pre_generate_log.py", line 1, in <module>
    from faker import Faker
ModuleNotFoundError: No module named 'faker'
[2023-08-25T11:12:26.383+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/workflow.py
[2023-08-25T11:12:26.468+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/workflow.py took 0.174 seconds
[2023-08-25T11:12:56.679+0000] {processor.py:157} INFO - Started process (PID=777) to work on /opt/airflow/dags/workflow.py
[2023-08-25T11:12:56.689+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/workflow.py for tasks to queue
[2023-08-25T11:12:56.696+0000] {logging_mixin.py:150} INFO - [2023-08-25T11:12:56.695+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/workflow.py
[2023-08-25T11:12:56.772+0000] {logging_mixin.py:150} INFO - [2023-08-25T11:12:56.766+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/workflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/workflow.py", line 1, in <module>
    from python_data_maker import pre_generate_log,generate_log,generate_item,generate_rating,generate_user
  File "/opt/airflow/dags/python_data_maker/pre_generate_log.py", line 1, in <module>
    from faker import Faker
ModuleNotFoundError: No module named 'faker'
[2023-08-25T11:12:56.777+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/workflow.py
[2023-08-25T11:12:56.828+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/workflow.py took 0.160 seconds
[2023-08-25T11:13:27.395+0000] {processor.py:157} INFO - Started process (PID=789) to work on /opt/airflow/dags/workflow.py
[2023-08-25T11:13:27.402+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/workflow.py for tasks to queue
[2023-08-25T11:13:27.408+0000] {logging_mixin.py:150} INFO - [2023-08-25T11:13:27.406+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/workflow.py
[2023-08-25T11:13:27.453+0000] {logging_mixin.py:150} INFO - [2023-08-25T11:13:27.443+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/workflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/workflow.py", line 1, in <module>
    from python_data_maker import pre_generate_log,generate_log,generate_item,generate_rating,generate_user
  File "/opt/airflow/dags/python_data_maker/pre_generate_log.py", line 1, in <module>
    from faker import Faker
ModuleNotFoundError: No module named 'faker'
[2023-08-25T11:13:27.457+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/workflow.py
[2023-08-25T11:13:27.505+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/workflow.py took 0.124 seconds
[2023-08-25T11:13:57.949+0000] {processor.py:157} INFO - Started process (PID=802) to work on /opt/airflow/dags/workflow.py
[2023-08-25T11:13:57.957+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/workflow.py for tasks to queue
[2023-08-25T11:13:57.963+0000] {logging_mixin.py:150} INFO - [2023-08-25T11:13:57.962+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/workflow.py
[2023-08-25T11:13:58.057+0000] {logging_mixin.py:150} INFO - [2023-08-25T11:13:58.024+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/workflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/workflow.py", line 1, in <module>
    from python_data_maker import pre_generate_log,generate_log,generate_item,generate_rating,generate_user
  File "/opt/airflow/dags/python_data_maker/pre_generate_log.py", line 1, in <module>
    from faker import Faker
ModuleNotFoundError: No module named 'faker'
[2023-08-25T11:13:58.069+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/workflow.py
[2023-08-25T11:13:58.284+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/workflow.py took 0.348 seconds
[2023-08-25T11:14:28.990+0000] {processor.py:157} INFO - Started process (PID=813) to work on /opt/airflow/dags/workflow.py
[2023-08-25T11:14:28.997+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/workflow.py for tasks to queue
[2023-08-25T11:14:29.002+0000] {logging_mixin.py:150} INFO - [2023-08-25T11:14:29.001+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/workflow.py
[2023-08-25T11:14:29.106+0000] {logging_mixin.py:150} INFO - [2023-08-25T11:14:29.081+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/workflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/workflow.py", line 1, in <module>
    from python_data_maker import pre_generate_log,generate_log,generate_item,generate_rating,generate_user
  File "/opt/airflow/dags/python_data_maker/pre_generate_log.py", line 1, in <module>
    from faker import Faker
ModuleNotFoundError: No module named 'faker'
[2023-08-25T11:14:29.118+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/workflow.py
[2023-08-25T11:14:29.233+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/workflow.py took 0.265 seconds
[2023-08-25T11:14:59.707+0000] {processor.py:157} INFO - Started process (PID=825) to work on /opt/airflow/dags/workflow.py
[2023-08-25T11:14:59.710+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/workflow.py for tasks to queue
[2023-08-25T11:14:59.731+0000] {logging_mixin.py:150} INFO - [2023-08-25T11:14:59.730+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/workflow.py
[2023-08-25T11:14:59.816+0000] {logging_mixin.py:150} INFO - [2023-08-25T11:14:59.806+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/workflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/workflow.py", line 1, in <module>
    from python_data_maker import pre_generate_log,generate_log,generate_item,generate_rating,generate_user
  File "/opt/airflow/dags/python_data_maker/pre_generate_log.py", line 1, in <module>
    from faker import Faker
ModuleNotFoundError: No module named 'faker'
[2023-08-25T11:14:59.818+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/workflow.py
[2023-08-25T11:14:59.932+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/workflow.py took 0.233 seconds
[2023-08-25T11:15:30.405+0000] {processor.py:157} INFO - Started process (PID=836) to work on /opt/airflow/dags/workflow.py
[2023-08-25T11:15:30.409+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/workflow.py for tasks to queue
[2023-08-25T11:15:30.412+0000] {logging_mixin.py:150} INFO - [2023-08-25T11:15:30.412+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/workflow.py
[2023-08-25T11:15:30.502+0000] {logging_mixin.py:150} INFO - [2023-08-25T11:15:30.483+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/workflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/workflow.py", line 1, in <module>
    from python_data_maker import pre_generate_log,generate_log,generate_item,generate_rating,generate_user
  File "/opt/airflow/dags/python_data_maker/pre_generate_log.py", line 1, in <module>
    from faker import Faker
ModuleNotFoundError: No module named 'faker'
[2023-08-25T11:15:30.507+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/workflow.py
[2023-08-25T11:15:30.586+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/workflow.py took 0.188 seconds
[2023-08-25T11:16:01.009+0000] {processor.py:157} INFO - Started process (PID=848) to work on /opt/airflow/dags/workflow.py
[2023-08-25T11:16:01.017+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/workflow.py for tasks to queue
[2023-08-25T11:16:01.020+0000] {logging_mixin.py:150} INFO - [2023-08-25T11:16:01.019+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/workflow.py
[2023-08-25T11:16:01.092+0000] {logging_mixin.py:150} INFO - [2023-08-25T11:16:01.070+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/workflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/workflow.py", line 1, in <module>
    from python_data_maker import pre_generate_log,generate_log,generate_item,generate_rating,generate_user
  File "/opt/airflow/dags/python_data_maker/pre_generate_log.py", line 1, in <module>
    from faker import Faker
ModuleNotFoundError: No module named 'faker'
[2023-08-25T11:16:01.102+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/workflow.py
[2023-08-25T11:16:01.200+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/workflow.py took 0.218 seconds
[2023-08-25T11:16:31.329+0000] {processor.py:157} INFO - Started process (PID=860) to work on /opt/airflow/dags/workflow.py
[2023-08-25T11:16:31.345+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/workflow.py for tasks to queue
[2023-08-25T11:16:31.352+0000] {logging_mixin.py:150} INFO - [2023-08-25T11:16:31.352+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/workflow.py
[2023-08-25T11:16:31.421+0000] {logging_mixin.py:150} INFO - [2023-08-25T11:16:31.403+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/workflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/workflow.py", line 1, in <module>
    from python_data_maker import pre_generate_log,generate_log,generate_item,generate_rating,generate_user
  File "/opt/airflow/dags/python_data_maker/pre_generate_log.py", line 1, in <module>
    from faker import Faker
ModuleNotFoundError: No module named 'faker'
[2023-08-25T11:16:31.427+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/workflow.py
[2023-08-25T11:16:31.511+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/workflow.py took 0.192 seconds
[2023-08-25T11:17:01.756+0000] {processor.py:157} INFO - Started process (PID=872) to work on /opt/airflow/dags/workflow.py
[2023-08-25T11:17:01.775+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/workflow.py for tasks to queue
[2023-08-25T11:17:01.803+0000] {logging_mixin.py:150} INFO - [2023-08-25T11:17:01.803+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/workflow.py
[2023-08-25T11:17:01.908+0000] {logging_mixin.py:150} INFO - [2023-08-25T11:17:01.886+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/workflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/workflow.py", line 1, in <module>
    from python_data_maker import pre_generate_log,generate_log,generate_item,generate_rating,generate_user
  File "/opt/airflow/dags/python_data_maker/pre_generate_log.py", line 1, in <module>
    from faker import Faker
ModuleNotFoundError: No module named 'faker'
[2023-08-25T11:17:01.910+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/workflow.py
[2023-08-25T11:17:02.063+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/workflow.py took 0.325 seconds
[2023-08-25T11:17:32.335+0000] {processor.py:157} INFO - Started process (PID=883) to work on /opt/airflow/dags/workflow.py
[2023-08-25T11:17:32.352+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/workflow.py for tasks to queue
[2023-08-25T11:17:32.358+0000] {logging_mixin.py:150} INFO - [2023-08-25T11:17:32.357+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/workflow.py
[2023-08-25T11:17:32.409+0000] {logging_mixin.py:150} INFO - [2023-08-25T11:17:32.397+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/workflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/workflow.py", line 1, in <module>
    from python_data_maker import pre_generate_log,generate_log,generate_item,generate_rating,generate_user
  File "/opt/airflow/dags/python_data_maker/pre_generate_log.py", line 1, in <module>
    from faker import Faker
ModuleNotFoundError: No module named 'faker'
[2023-08-25T11:17:32.413+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/workflow.py
[2023-08-25T11:17:32.499+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/workflow.py took 0.180 seconds
[2023-08-25T11:18:02.806+0000] {processor.py:157} INFO - Started process (PID=894) to work on /opt/airflow/dags/workflow.py
[2023-08-25T11:18:02.811+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/workflow.py for tasks to queue
[2023-08-25T11:18:02.819+0000] {logging_mixin.py:150} INFO - [2023-08-25T11:18:02.815+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/workflow.py
[2023-08-25T11:18:02.874+0000] {logging_mixin.py:150} INFO - [2023-08-25T11:18:02.867+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/workflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/workflow.py", line 1, in <module>
    from python_data_maker import pre_generate_log,generate_log,generate_item,generate_rating,generate_user
  File "/opt/airflow/dags/python_data_maker/pre_generate_log.py", line 1, in <module>
    from faker import Faker
ModuleNotFoundError: No module named 'faker'
[2023-08-25T11:18:02.876+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/workflow.py
[2023-08-25T11:18:02.930+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/workflow.py took 0.139 seconds
