[2023-09-15T15:33:32.791+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: eCommerce_ETL_dag.branching manual__2023-09-15T15:28:27.800121+00:00 [queued]>
[2023-09-15T15:33:32.823+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: eCommerce_ETL_dag.branching manual__2023-09-15T15:28:27.800121+00:00 [queued]>
[2023-09-15T15:33:32.830+0000] {taskinstance.py:1308} INFO - Starting attempt 2 of 2
[2023-09-15T15:33:32.870+0000] {taskinstance.py:1327} INFO - Executing <Task(BranchPythonOperator): branching> on 2023-09-15 15:28:27.800121+00:00
[2023-09-15T15:33:32.879+0000] {standard_task_runner.py:57} INFO - Started process 354 to run task
[2023-09-15T15:33:32.888+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'eCommerce_ETL_dag', 'branching', 'manual__2023-09-15T15:28:27.800121+00:00', '--job-id', '7', '--raw', '--subdir', 'DAGS_FOLDER/workflow.py', '--cfg-path', '/tmp/tmphjan98xu']
[2023-09-15T15:33:32.894+0000] {standard_task_runner.py:85} INFO - Job 7: Subtask branching
[2023-09-15T15:33:32.969+0000] {task_command.py:410} INFO - Running <TaskInstance: eCommerce_ETL_dag.branching manual__2023-09-15T15:28:27.800121+00:00 [running]> on host 228226a2581e
[2023-09-15T15:33:33.062+0000] {taskinstance.py:1545} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='eCommerce_ETL_dag' AIRFLOW_CTX_TASK_ID='branching' AIRFLOW_CTX_EXECUTION_DATE='2023-09-15T15:28:27.800121+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-09-15T15:28:27.800121+00:00'
[2023-09-15T15:33:33.073+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 215, in execute
    branch = super().execute(context)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/workflow.py", line 27, in check_table_count
    check = cursor.fetchone()[0]
TypeError: 'NoneType' object is not subscriptable
[2023-09-15T15:33:33.090+0000] {taskinstance.py:1345} INFO - Marking task as FAILED. dag_id=eCommerce_ETL_dag, task_id=branching, execution_date=20230915T152827, start_date=20230915T153332, end_date=20230915T153333
[2023-09-15T15:33:33.113+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 7 for task branching ('NoneType' object is not subscriptable; 354)
[2023-09-15T15:33:33.143+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-09-15T15:33:33.189+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
